//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: acl.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AclEntryProto_AclEntryScopeProto int32

const (
	AclEntryProto_ACCESS  AclEntryProto_AclEntryScopeProto = 0
	AclEntryProto_DEFAULT AclEntryProto_AclEntryScopeProto = 1
)

// Enum value maps for AclEntryProto_AclEntryScopeProto.
var (
	AclEntryProto_AclEntryScopeProto_name = map[int32]string{
		0: "ACCESS",
		1: "DEFAULT",
	}
	AclEntryProto_AclEntryScopeProto_value = map[string]int32{
		"ACCESS":  0,
		"DEFAULT": 1,
	}
)

func (x AclEntryProto_AclEntryScopeProto) Enum() *AclEntryProto_AclEntryScopeProto {
	p := new(AclEntryProto_AclEntryScopeProto)
	*p = x
	return p
}

func (x AclEntryProto_AclEntryScopeProto) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AclEntryProto_AclEntryScopeProto) Descriptor() protoreflect.EnumDescriptor {
	return file_acl_proto_enumTypes[0].Descriptor()
}

func (AclEntryProto_AclEntryScopeProto) Type() protoreflect.EnumType {
	return &file_acl_proto_enumTypes[0]
}

func (x AclEntryProto_AclEntryScopeProto) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AclEntryProto_AclEntryScopeProto) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AclEntryProto_AclEntryScopeProto(num)
	return nil
}

// Deprecated: Use AclEntryProto_AclEntryScopeProto.Descriptor instead.
func (AclEntryProto_AclEntryScopeProto) EnumDescriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{1, 0}
}

type AclEntryProto_AclEntryTypeProto int32

const (
	AclEntryProto_USER  AclEntryProto_AclEntryTypeProto = 0
	AclEntryProto_GROUP AclEntryProto_AclEntryTypeProto = 1
	AclEntryProto_MASK  AclEntryProto_AclEntryTypeProto = 2
	AclEntryProto_OTHER AclEntryProto_AclEntryTypeProto = 3
)

// Enum value maps for AclEntryProto_AclEntryTypeProto.
var (
	AclEntryProto_AclEntryTypeProto_name = map[int32]string{
		0: "USER",
		1: "GROUP",
		2: "MASK",
		3: "OTHER",
	}
	AclEntryProto_AclEntryTypeProto_value = map[string]int32{
		"USER":  0,
		"GROUP": 1,
		"MASK":  2,
		"OTHER": 3,
	}
)

func (x AclEntryProto_AclEntryTypeProto) Enum() *AclEntryProto_AclEntryTypeProto {
	p := new(AclEntryProto_AclEntryTypeProto)
	*p = x
	return p
}

func (x AclEntryProto_AclEntryTypeProto) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AclEntryProto_AclEntryTypeProto) Descriptor() protoreflect.EnumDescriptor {
	return file_acl_proto_enumTypes[1].Descriptor()
}

func (AclEntryProto_AclEntryTypeProto) Type() protoreflect.EnumType {
	return &file_acl_proto_enumTypes[1]
}

func (x AclEntryProto_AclEntryTypeProto) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AclEntryProto_AclEntryTypeProto) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AclEntryProto_AclEntryTypeProto(num)
	return nil
}

// Deprecated: Use AclEntryProto_AclEntryTypeProto.Descriptor instead.
func (AclEntryProto_AclEntryTypeProto) EnumDescriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{1, 1}
}

type AclEntryProto_FsActionProto int32

const (
	AclEntryProto_NONE          AclEntryProto_FsActionProto = 0
	AclEntryProto_EXECUTE       AclEntryProto_FsActionProto = 1
	AclEntryProto_WRITE         AclEntryProto_FsActionProto = 2
	AclEntryProto_WRITE_EXECUTE AclEntryProto_FsActionProto = 3
	AclEntryProto_READ          AclEntryProto_FsActionProto = 4
	AclEntryProto_READ_EXECUTE  AclEntryProto_FsActionProto = 5
	AclEntryProto_READ_WRITE    AclEntryProto_FsActionProto = 6
	AclEntryProto_PERM_ALL      AclEntryProto_FsActionProto = 7
)

// Enum value maps for AclEntryProto_FsActionProto.
var (
	AclEntryProto_FsActionProto_name = map[int32]string{
		0: "NONE",
		1: "EXECUTE",
		2: "WRITE",
		3: "WRITE_EXECUTE",
		4: "READ",
		5: "READ_EXECUTE",
		6: "READ_WRITE",
		7: "PERM_ALL",
	}
	AclEntryProto_FsActionProto_value = map[string]int32{
		"NONE":          0,
		"EXECUTE":       1,
		"WRITE":         2,
		"WRITE_EXECUTE": 3,
		"READ":          4,
		"READ_EXECUTE":  5,
		"READ_WRITE":    6,
		"PERM_ALL":      7,
	}
)

func (x AclEntryProto_FsActionProto) Enum() *AclEntryProto_FsActionProto {
	p := new(AclEntryProto_FsActionProto)
	*p = x
	return p
}

func (x AclEntryProto_FsActionProto) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AclEntryProto_FsActionProto) Descriptor() protoreflect.EnumDescriptor {
	return file_acl_proto_enumTypes[2].Descriptor()
}

func (AclEntryProto_FsActionProto) Type() protoreflect.EnumType {
	return &file_acl_proto_enumTypes[2]
}

func (x AclEntryProto_FsActionProto) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AclEntryProto_FsActionProto) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AclEntryProto_FsActionProto(num)
	return nil
}

// Deprecated: Use AclEntryProto_FsActionProto.Descriptor instead.
func (AclEntryProto_FsActionProto) EnumDescriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{1, 2}
}

// *
// File or Directory permision - same spec as posix
type FsPermissionProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Perm          *uint32                `protobuf:"varint,1,req,name=perm" json:"perm,omitempty"` // Actually a short - only 16bits used
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsPermissionProto) Reset() {
	*x = FsPermissionProto{}
	mi := &file_acl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsPermissionProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsPermissionProto) ProtoMessage() {}

func (x *FsPermissionProto) ProtoReflect() protoreflect.Message {
	mi := &file_acl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsPermissionProto.ProtoReflect.Descriptor instead.
func (*FsPermissionProto) Descriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{0}
}

func (x *FsPermissionProto) GetPerm() uint32 {
	if x != nil && x.Perm != nil {
		return *x.Perm
	}
	return 0
}

type AclEntryProto struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Type          *AclEntryProto_AclEntryTypeProto  `protobuf:"varint,1,req,name=type,enum=hadoop.hdfs.AclEntryProto_AclEntryTypeProto" json:"type,omitempty"`
	Scope         *AclEntryProto_AclEntryScopeProto `protobuf:"varint,2,req,name=scope,enum=hadoop.hdfs.AclEntryProto_AclEntryScopeProto" json:"scope,omitempty"`
	Permissions   *AclEntryProto_FsActionProto      `protobuf:"varint,3,req,name=permissions,enum=hadoop.hdfs.AclEntryProto_FsActionProto" json:"permissions,omitempty"`
	Name          *string                           `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AclEntryProto) Reset() {
	*x = AclEntryProto{}
	mi := &file_acl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AclEntryProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AclEntryProto) ProtoMessage() {}

func (x *AclEntryProto) ProtoReflect() protoreflect.Message {
	mi := &file_acl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AclEntryProto.ProtoReflect.Descriptor instead.
func (*AclEntryProto) Descriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{1}
}

func (x *AclEntryProto) GetType() AclEntryProto_AclEntryTypeProto {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return AclEntryProto_USER
}

func (x *AclEntryProto) GetScope() AclEntryProto_AclEntryScopeProto {
	if x != nil && x.Scope != nil {
		return *x.Scope
	}
	return AclEntryProto_ACCESS
}

func (x *AclEntryProto) GetPermissions() AclEntryProto_FsActionProto {
	if x != nil && x.Permissions != nil {
		return *x.Permissions
	}
	return AclEntryProto_NONE
}

func (x *AclEntryProto) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type AclStatusProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         *string                `protobuf:"bytes,1,req,name=owner" json:"owner,omitempty"`
	Group         *string                `protobuf:"bytes,2,req,name=group" json:"group,omitempty"`
	Sticky        *bool                  `protobuf:"varint,3,req,name=sticky" json:"sticky,omitempty"`
	Entries       []*AclEntryProto       `protobuf:"bytes,4,rep,name=entries" json:"entries,omitempty"`
	Permission    *FsPermissionProto     `protobuf:"bytes,5,opt,name=permission" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AclStatusProto) Reset() {
	*x = AclStatusProto{}
	mi := &file_acl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AclStatusProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AclStatusProto) ProtoMessage() {}

func (x *AclStatusProto) ProtoReflect() protoreflect.Message {
	mi := &file_acl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AclStatusProto.ProtoReflect.Descriptor instead.
func (*AclStatusProto) Descriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{2}
}

func (x *AclStatusProto) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

func (x *AclStatusProto) GetGroup() string {
	if x != nil && x.Group != nil {
		return *x.Group
	}
	return ""
}

func (x *AclStatusProto) GetSticky() bool {
	if x != nil && x.Sticky != nil {
		return *x.Sticky
	}
	return false
}

func (x *AclStatusProto) GetEntries() []*AclEntryProto {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *AclStatusProto) GetPermission() *FsPermissionProto {
	if x != nil {
		return x.Permission
	}
	return nil
}

type ModifyAclEntriesRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Src           *string                `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	AclSpec       []*AclEntryProto       `protobuf:"bytes,2,rep,name=aclSpec" json:"aclSpec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyAclEntriesRequestProto) Reset() {
	*x = ModifyAclEntriesRequestProto{}
	mi := &file_acl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyAclEntriesRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyAclEntriesRequestProto) ProtoMessage() {}

func (x *ModifyAclEntriesRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_acl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyAclEntriesRequestProto.ProtoReflect.Descriptor instead.
func (*ModifyAclEntriesRequestProto) Descriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{3}
}

func (x *ModifyAclEntriesRequestProto) GetSrc() string {
	if x != nil && x.Src != nil {
		return *x.Src
	}
	return ""
}

func (x *ModifyAclEntriesRequestProto) GetAclSpec() []*AclEntryProto {
	if x != nil {
		return x.AclSpec
	}
	return nil
}

type ModifyAclEntriesResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyAclEntriesResponseProto) Reset() {
	*x = ModifyAclEntriesResponseProto{}
	mi := &file_acl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyAclEntriesResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyAclEntriesResponseProto) ProtoMessage() {}

func (x *ModifyAclEntriesResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_acl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyAclEntriesResponseProto.ProtoReflect.Descriptor instead.
func (*ModifyAclEntriesResponseProto) Descriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{4}
}

type RemoveAclRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Src           *string                `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAclRequestProto) Reset() {
	*x = RemoveAclRequestProto{}
	mi := &file_acl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAclRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAclRequestProto) ProtoMessage() {}

func (x *RemoveAclRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_acl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAclRequestProto.ProtoReflect.Descriptor instead.
func (*RemoveAclRequestProto) Descriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveAclRequestProto) GetSrc() string {
	if x != nil && x.Src != nil {
		return *x.Src
	}
	return ""
}

type RemoveAclResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAclResponseProto) Reset() {
	*x = RemoveAclResponseProto{}
	mi := &file_acl_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAclResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAclResponseProto) ProtoMessage() {}

func (x *RemoveAclResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_acl_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAclResponseProto.ProtoReflect.Descriptor instead.
func (*RemoveAclResponseProto) Descriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{6}
}

type RemoveAclEntriesRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Src           *string                `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	AclSpec       []*AclEntryProto       `protobuf:"bytes,2,rep,name=aclSpec" json:"aclSpec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAclEntriesRequestProto) Reset() {
	*x = RemoveAclEntriesRequestProto{}
	mi := &file_acl_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAclEntriesRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAclEntriesRequestProto) ProtoMessage() {}

func (x *RemoveAclEntriesRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_acl_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAclEntriesRequestProto.ProtoReflect.Descriptor instead.
func (*RemoveAclEntriesRequestProto) Descriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveAclEntriesRequestProto) GetSrc() string {
	if x != nil && x.Src != nil {
		return *x.Src
	}
	return ""
}

func (x *RemoveAclEntriesRequestProto) GetAclSpec() []*AclEntryProto {
	if x != nil {
		return x.AclSpec
	}
	return nil
}

type RemoveAclEntriesResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAclEntriesResponseProto) Reset() {
	*x = RemoveAclEntriesResponseProto{}
	mi := &file_acl_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAclEntriesResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAclEntriesResponseProto) ProtoMessage() {}

func (x *RemoveAclEntriesResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_acl_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAclEntriesResponseProto.ProtoReflect.Descriptor instead.
func (*RemoveAclEntriesResponseProto) Descriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{8}
}

type RemoveDefaultAclRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Src           *string                `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveDefaultAclRequestProto) Reset() {
	*x = RemoveDefaultAclRequestProto{}
	mi := &file_acl_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveDefaultAclRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDefaultAclRequestProto) ProtoMessage() {}

func (x *RemoveDefaultAclRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_acl_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDefaultAclRequestProto.ProtoReflect.Descriptor instead.
func (*RemoveDefaultAclRequestProto) Descriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveDefaultAclRequestProto) GetSrc() string {
	if x != nil && x.Src != nil {
		return *x.Src
	}
	return ""
}

type RemoveDefaultAclResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveDefaultAclResponseProto) Reset() {
	*x = RemoveDefaultAclResponseProto{}
	mi := &file_acl_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveDefaultAclResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDefaultAclResponseProto) ProtoMessage() {}

func (x *RemoveDefaultAclResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_acl_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDefaultAclResponseProto.ProtoReflect.Descriptor instead.
func (*RemoveDefaultAclResponseProto) Descriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{10}
}

type SetAclRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Src           *string                `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	AclSpec       []*AclEntryProto       `protobuf:"bytes,2,rep,name=aclSpec" json:"aclSpec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAclRequestProto) Reset() {
	*x = SetAclRequestProto{}
	mi := &file_acl_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAclRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAclRequestProto) ProtoMessage() {}

func (x *SetAclRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_acl_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAclRequestProto.ProtoReflect.Descriptor instead.
func (*SetAclRequestProto) Descriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{11}
}

func (x *SetAclRequestProto) GetSrc() string {
	if x != nil && x.Src != nil {
		return *x.Src
	}
	return ""
}

func (x *SetAclRequestProto) GetAclSpec() []*AclEntryProto {
	if x != nil {
		return x.AclSpec
	}
	return nil
}

type SetAclResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAclResponseProto) Reset() {
	*x = SetAclResponseProto{}
	mi := &file_acl_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAclResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAclResponseProto) ProtoMessage() {}

func (x *SetAclResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_acl_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAclResponseProto.ProtoReflect.Descriptor instead.
func (*SetAclResponseProto) Descriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{12}
}

type GetAclStatusRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Src           *string                `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAclStatusRequestProto) Reset() {
	*x = GetAclStatusRequestProto{}
	mi := &file_acl_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAclStatusRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAclStatusRequestProto) ProtoMessage() {}

func (x *GetAclStatusRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_acl_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAclStatusRequestProto.ProtoReflect.Descriptor instead.
func (*GetAclStatusRequestProto) Descriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{13}
}

func (x *GetAclStatusRequestProto) GetSrc() string {
	if x != nil && x.Src != nil {
		return *x.Src
	}
	return ""
}

type GetAclStatusResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *AclStatusProto        `protobuf:"bytes,1,req,name=result" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAclStatusResponseProto) Reset() {
	*x = GetAclStatusResponseProto{}
	mi := &file_acl_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAclStatusResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAclStatusResponseProto) ProtoMessage() {}

func (x *GetAclStatusResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_acl_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAclStatusResponseProto.ProtoReflect.Descriptor instead.
func (*GetAclStatusResponseProto) Descriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{14}
}

func (x *GetAclStatusResponseProto) GetResult() *AclStatusProto {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_acl_proto protoreflect.FileDescriptor

const file_acl_proto_rawDesc = "" +
	"\n" +
	"\tacl.proto\x12\vhadoop.hdfs\"'\n" +
	"\x11FsPermissionProto\x12\x12\n" +
	"\x04perm\x18\x01 \x02(\rR\x04perm\"\xe4\x03\n" +
	"\rAclEntryProto\x12@\n" +
	"\x04type\x18\x01 \x02(\x0e2,.hadoop.hdfs.AclEntryProto.AclEntryTypeProtoR\x04type\x12C\n" +
	"\x05scope\x18\x02 \x02(\x0e2-.hadoop.hdfs.AclEntryProto.AclEntryScopeProtoR\x05scope\x12J\n" +
	"\vpermissions\x18\x03 \x02(\x0e2(.hadoop.hdfs.AclEntryProto.FsActionProtoR\vpermissions\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"-\n" +
	"\x12AclEntryScopeProto\x12\n" +
	"\n" +
	"\x06ACCESS\x10\x00\x12\v\n" +
	"\aDEFAULT\x10\x01\"=\n" +
	"\x11AclEntryTypeProto\x12\b\n" +
	"\x04USER\x10\x00\x12\t\n" +
	"\x05GROUP\x10\x01\x12\b\n" +
	"\x04MASK\x10\x02\x12\t\n" +
	"\x05OTHER\x10\x03\"~\n" +
	"\rFsActionProto\x12\b\n" +
	"\x04NONE\x10\x00\x12\v\n" +
	"\aEXECUTE\x10\x01\x12\t\n" +
	"\x05WRITE\x10\x02\x12\x11\n" +
	"\rWRITE_EXECUTE\x10\x03\x12\b\n" +
	"\x04READ\x10\x04\x12\x10\n" +
	"\fREAD_EXECUTE\x10\x05\x12\x0e\n" +
	"\n" +
	"READ_WRITE\x10\x06\x12\f\n" +
	"\bPERM_ALL\x10\a\"\xca\x01\n" +
	"\x0eAclStatusProto\x12\x14\n" +
	"\x05owner\x18\x01 \x02(\tR\x05owner\x12\x14\n" +
	"\x05group\x18\x02 \x02(\tR\x05group\x12\x16\n" +
	"\x06sticky\x18\x03 \x02(\bR\x06sticky\x124\n" +
	"\aentries\x18\x04 \x03(\v2\x1a.hadoop.hdfs.AclEntryProtoR\aentries\x12>\n" +
	"\n" +
	"permission\x18\x05 \x01(\v2\x1e.hadoop.hdfs.FsPermissionProtoR\n" +
	"permission\"f\n" +
	"\x1cModifyAclEntriesRequestProto\x12\x10\n" +
	"\x03src\x18\x01 \x02(\tR\x03src\x124\n" +
	"\aaclSpec\x18\x02 \x03(\v2\x1a.hadoop.hdfs.AclEntryProtoR\aaclSpec\"\x1f\n" +
	"\x1dModifyAclEntriesResponseProto\")\n" +
	"\x15RemoveAclRequestProto\x12\x10\n" +
	"\x03src\x18\x01 \x02(\tR\x03src\"\x18\n" +
	"\x16RemoveAclResponseProto\"f\n" +
	"\x1cRemoveAclEntriesRequestProto\x12\x10\n" +
	"\x03src\x18\x01 \x02(\tR\x03src\x124\n" +
	"\aaclSpec\x18\x02 \x03(\v2\x1a.hadoop.hdfs.AclEntryProtoR\aaclSpec\"\x1f\n" +
	"\x1dRemoveAclEntriesResponseProto\"0\n" +
	"\x1cRemoveDefaultAclRequestProto\x12\x10\n" +
	"\x03src\x18\x01 \x02(\tR\x03src\"\x1f\n" +
	"\x1dRemoveDefaultAclResponseProto\"\\\n" +
	"\x12SetAclRequestProto\x12\x10\n" +
	"\x03src\x18\x01 \x02(\tR\x03src\x124\n" +
	"\aaclSpec\x18\x02 \x03(\v2\x1a.hadoop.hdfs.AclEntryProtoR\aaclSpec\"\x15\n" +
	"\x13SetAclResponseProto\",\n" +
	"\x18GetAclStatusRequestProto\x12\x10\n" +
	"\x03src\x18\x01 \x02(\tR\x03src\"P\n" +
	"\x19GetAclStatusResponseProto\x123\n" +
	"\x06result\x18\x01 \x02(\v2\x1b.hadoop.hdfs.AclStatusProtoR\x06resultBj\n" +
	"%org.apache.hadoop.hdfs.protocol.protoB\tAclProtosZ3github.com/nirvam/go-hdfs-fsimage/pkg/fsimage/types\xa0\x01\x01"

var (
	file_acl_proto_rawDescOnce sync.Once
	file_acl_proto_rawDescData []byte
)

func file_acl_proto_rawDescGZIP() []byte {
	file_acl_proto_rawDescOnce.Do(func() {
		file_acl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_acl_proto_rawDesc), len(file_acl_proto_rawDesc)))
	})
	return file_acl_proto_rawDescData
}

var file_acl_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_acl_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_acl_proto_goTypes = []any{
	(AclEntryProto_AclEntryScopeProto)(0), // 0: hadoop.hdfs.AclEntryProto.AclEntryScopeProto
	(AclEntryProto_AclEntryTypeProto)(0),  // 1: hadoop.hdfs.AclEntryProto.AclEntryTypeProto
	(AclEntryProto_FsActionProto)(0),      // 2: hadoop.hdfs.AclEntryProto.FsActionProto
	(*FsPermissionProto)(nil),             // 3: hadoop.hdfs.FsPermissionProto
	(*AclEntryProto)(nil),                 // 4: hadoop.hdfs.AclEntryProto
	(*AclStatusProto)(nil),                // 5: hadoop.hdfs.AclStatusProto
	(*ModifyAclEntriesRequestProto)(nil),  // 6: hadoop.hdfs.ModifyAclEntriesRequestProto
	(*ModifyAclEntriesResponseProto)(nil), // 7: hadoop.hdfs.ModifyAclEntriesResponseProto
	(*RemoveAclRequestProto)(nil),         // 8: hadoop.hdfs.RemoveAclRequestProto
	(*RemoveAclResponseProto)(nil),        // 9: hadoop.hdfs.RemoveAclResponseProto
	(*RemoveAclEntriesRequestProto)(nil),  // 10: hadoop.hdfs.RemoveAclEntriesRequestProto
	(*RemoveAclEntriesResponseProto)(nil), // 11: hadoop.hdfs.RemoveAclEntriesResponseProto
	(*RemoveDefaultAclRequestProto)(nil),  // 12: hadoop.hdfs.RemoveDefaultAclRequestProto
	(*RemoveDefaultAclResponseProto)(nil), // 13: hadoop.hdfs.RemoveDefaultAclResponseProto
	(*SetAclRequestProto)(nil),            // 14: hadoop.hdfs.SetAclRequestProto
	(*SetAclResponseProto)(nil),           // 15: hadoop.hdfs.SetAclResponseProto
	(*GetAclStatusRequestProto)(nil),      // 16: hadoop.hdfs.GetAclStatusRequestProto
	(*GetAclStatusResponseProto)(nil),     // 17: hadoop.hdfs.GetAclStatusResponseProto
}
var file_acl_proto_depIdxs = []int32{
	1, // 0: hadoop.hdfs.AclEntryProto.type:type_name -> hadoop.hdfs.AclEntryProto.AclEntryTypeProto
	0, // 1: hadoop.hdfs.AclEntryProto.scope:type_name -> hadoop.hdfs.AclEntryProto.AclEntryScopeProto
	2, // 2: hadoop.hdfs.AclEntryProto.permissions:type_name -> hadoop.hdfs.AclEntryProto.FsActionProto
	4, // 3: hadoop.hdfs.AclStatusProto.entries:type_name -> hadoop.hdfs.AclEntryProto
	3, // 4: hadoop.hdfs.AclStatusProto.permission:type_name -> hadoop.hdfs.FsPermissionProto
	4, // 5: hadoop.hdfs.ModifyAclEntriesRequestProto.aclSpec:type_name -> hadoop.hdfs.AclEntryProto
	4, // 6: hadoop.hdfs.RemoveAclEntriesRequestProto.aclSpec:type_name -> hadoop.hdfs.AclEntryProto
	4, // 7: hadoop.hdfs.SetAclRequestProto.aclSpec:type_name -> hadoop.hdfs.AclEntryProto
	5, // 8: hadoop.hdfs.GetAclStatusResponseProto.result:type_name -> hadoop.hdfs.AclStatusProto
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_acl_proto_init() }
func file_acl_proto_init() {
	if File_acl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_acl_proto_rawDesc), len(file_acl_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_acl_proto_goTypes,
		DependencyIndexes: file_acl_proto_depIdxs,
		EnumInfos:         file_acl_proto_enumTypes,
		MessageInfos:      file_acl_proto_msgTypes,
	}.Build()
	File_acl_proto = out.File
	file_acl_proto_goTypes = nil
	file_acl_proto_depIdxs = nil
}
