//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: fsimage.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type INodeSection_INode_Type int32

const (
	INodeSection_INode_FILE      INodeSection_INode_Type = 1
	INodeSection_INode_DIRECTORY INodeSection_INode_Type = 2
	INodeSection_INode_SYMLINK   INodeSection_INode_Type = 3
)

// Enum value maps for INodeSection_INode_Type.
var (
	INodeSection_INode_Type_name = map[int32]string{
		1: "FILE",
		2: "DIRECTORY",
		3: "SYMLINK",
	}
	INodeSection_INode_Type_value = map[string]int32{
		"FILE":      1,
		"DIRECTORY": 2,
		"SYMLINK":   3,
	}
)

func (x INodeSection_INode_Type) Enum() *INodeSection_INode_Type {
	p := new(INodeSection_INode_Type)
	*p = x
	return p
}

func (x INodeSection_INode_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (INodeSection_INode_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_fsimage_proto_enumTypes[0].Descriptor()
}

func (INodeSection_INode_Type) Type() protoreflect.EnumType {
	return &file_fsimage_proto_enumTypes[0]
}

func (x INodeSection_INode_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *INodeSection_INode_Type) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = INodeSection_INode_Type(num)
	return nil
}

// Deprecated: Use INodeSection_INode_Type.Descriptor instead.
func (INodeSection_INode_Type) EnumDescriptor() ([]byte, []int) {
	return file_fsimage_proto_rawDescGZIP(), []int{2, 9, 0}
}

type SnapshotDiffSection_DiffEntry_Type int32

const (
	SnapshotDiffSection_DiffEntry_FILEDIFF      SnapshotDiffSection_DiffEntry_Type = 1
	SnapshotDiffSection_DiffEntry_DIRECTORYDIFF SnapshotDiffSection_DiffEntry_Type = 2
)

// Enum value maps for SnapshotDiffSection_DiffEntry_Type.
var (
	SnapshotDiffSection_DiffEntry_Type_name = map[int32]string{
		1: "FILEDIFF",
		2: "DIRECTORYDIFF",
	}
	SnapshotDiffSection_DiffEntry_Type_value = map[string]int32{
		"FILEDIFF":      1,
		"DIRECTORYDIFF": 2,
	}
)

func (x SnapshotDiffSection_DiffEntry_Type) Enum() *SnapshotDiffSection_DiffEntry_Type {
	p := new(SnapshotDiffSection_DiffEntry_Type)
	*p = x
	return p
}

func (x SnapshotDiffSection_DiffEntry_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SnapshotDiffSection_DiffEntry_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_fsimage_proto_enumTypes[1].Descriptor()
}

func (SnapshotDiffSection_DiffEntry_Type) Type() protoreflect.EnumType {
	return &file_fsimage_proto_enumTypes[1]
}

func (x SnapshotDiffSection_DiffEntry_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SnapshotDiffSection_DiffEntry_Type) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SnapshotDiffSection_DiffEntry_Type(num)
	return nil
}

// Deprecated: Use SnapshotDiffSection_DiffEntry_Type.Descriptor instead.
func (SnapshotDiffSection_DiffEntry_Type) EnumDescriptor() ([]byte, []int) {
	return file_fsimage_proto_rawDescGZIP(), []int{7, 3, 0}
}

type FileSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The version of the above EBNF grammars.
	OndiskVersion *uint32 `protobuf:"varint,1,req,name=ondiskVersion" json:"ondiskVersion,omitempty"`
	// layoutVersion describes which features are available in the
	// FSImage.
	LayoutVersion *uint32                `protobuf:"varint,2,req,name=layoutVersion" json:"layoutVersion,omitempty"`
	Codec         *string                `protobuf:"bytes,3,opt,name=codec" json:"codec,omitempty"`
	Sections      []*FileSummary_Section `protobuf:"bytes,4,rep,name=sections" json:"sections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileSummary) Reset() {
	*x = FileSummary{}
	mi := &file_fsimage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSummary) ProtoMessage() {}

func (x *FileSummary) ProtoReflect() protoreflect.Message {
	mi := &file_fsimage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSummary.ProtoReflect.Descriptor instead.
func (*FileSummary) Descriptor() ([]byte, []int) {
	return file_fsimage_proto_rawDescGZIP(), []int{0}
}

func (x *FileSummary) GetOndiskVersion() uint32 {
	if x != nil && x.OndiskVersion != nil {
		return *x.OndiskVersion
	}
	return 0
}

func (x *FileSummary) GetLayoutVersion() uint32 {
	if x != nil && x.LayoutVersion != nil {
		return *x.LayoutVersion
	}
	return 0
}

func (x *FileSummary) GetCodec() string {
	if x != nil && x.Codec != nil {
		return *x.Codec
	}
	return ""
}

func (x *FileSummary) GetSections() []*FileSummary_Section {
	if x != nil {
		return x.Sections
	}
	return nil
}

// *
// Name: NS_INFO
type NameSystemSection struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId                 *uint32                `protobuf:"varint,1,opt,name=namespaceId" json:"namespaceId,omitempty"`
	GenstampV1                  *uint64                `protobuf:"varint,2,opt,name=genstampV1" json:"genstampV1,omitempty"` // legacy generation stamp
	GenstampV2                  *uint64                `protobuf:"varint,3,opt,name=genstampV2" json:"genstampV2,omitempty"` // generation stamp of latest version
	GenstampV1Limit             *uint64                `protobuf:"varint,4,opt,name=genstampV1Limit" json:"genstampV1Limit,omitempty"`
	LastAllocatedBlockId        *uint64                `protobuf:"varint,5,opt,name=lastAllocatedBlockId" json:"lastAllocatedBlockId,omitempty"`
	TransactionId               *uint64                `protobuf:"varint,6,opt,name=transactionId" json:"transactionId,omitempty"`
	RollingUpgradeStartTime     *uint64                `protobuf:"varint,7,opt,name=rollingUpgradeStartTime" json:"rollingUpgradeStartTime,omitempty"`
	LastAllocatedStripedBlockId *uint64                `protobuf:"varint,8,opt,name=lastAllocatedStripedBlockId" json:"lastAllocatedStripedBlockId,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *NameSystemSection) Reset() {
	*x = NameSystemSection{}
	mi := &file_fsimage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NameSystemSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameSystemSection) ProtoMessage() {}

func (x *NameSystemSection) ProtoReflect() protoreflect.Message {
	mi := &file_fsimage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameSystemSection.ProtoReflect.Descriptor instead.
func (*NameSystemSection) Descriptor() ([]byte, []int) {
	return file_fsimage_proto_rawDescGZIP(), []int{1}
}

func (x *NameSystemSection) GetNamespaceId() uint32 {
	if x != nil && x.NamespaceId != nil {
		return *x.NamespaceId
	}
	return 0
}

func (x *NameSystemSection) GetGenstampV1() uint64 {
	if x != nil && x.GenstampV1 != nil {
		return *x.GenstampV1
	}
	return 0
}

func (x *NameSystemSection) GetGenstampV2() uint64 {
	if x != nil && x.GenstampV2 != nil {
		return *x.GenstampV2
	}
	return 0
}

func (x *NameSystemSection) GetGenstampV1Limit() uint64 {
	if x != nil && x.GenstampV1Limit != nil {
		return *x.GenstampV1Limit
	}
	return 0
}

func (x *NameSystemSection) GetLastAllocatedBlockId() uint64 {
	if x != nil && x.LastAllocatedBlockId != nil {
		return *x.LastAllocatedBlockId
	}
	return 0
}

func (x *NameSystemSection) GetTransactionId() uint64 {
	if x != nil && x.TransactionId != nil {
		return *x.TransactionId
	}
	return 0
}

func (x *NameSystemSection) GetRollingUpgradeStartTime() uint64 {
	if x != nil && x.RollingUpgradeStartTime != nil {
		return *x.RollingUpgradeStartTime
	}
	return 0
}

func (x *NameSystemSection) GetLastAllocatedStripedBlockId() uint64 {
	if x != nil && x.LastAllocatedStripedBlockId != nil {
		return *x.LastAllocatedStripedBlockId
	}
	return 0
}

// *
// Permission is serialized as a 64-bit long. [0:24):[25:48):[48:64) (in Big Endian).
// The first and the second parts are the string ids of the user and
// group name, and the last 16 bits are the permission bits.
//
// Name: INODE
type INodeSection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastInodeId   *uint64                `protobuf:"varint,1,opt,name=lastInodeId" json:"lastInodeId,omitempty"`
	NumInodes     *uint64                `protobuf:"varint,2,opt,name=numInodes" json:"numInodes,omitempty"` // repeated INodes..
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *INodeSection) Reset() {
	*x = INodeSection{}
	mi := &file_fsimage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *INodeSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*INodeSection) ProtoMessage() {}

func (x *INodeSection) ProtoReflect() protoreflect.Message {
	mi := &file_fsimage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use INodeSection.ProtoReflect.Descriptor instead.
func (*INodeSection) Descriptor() ([]byte, []int) {
	return file_fsimage_proto_rawDescGZIP(), []int{2}
}

func (x *INodeSection) GetLastInodeId() uint64 {
	if x != nil && x.LastInodeId != nil {
		return *x.LastInodeId
	}
	return 0
}

func (x *INodeSection) GetNumInodes() uint64 {
	if x != nil && x.NumInodes != nil {
		return *x.NumInodes
	}
	return 0
}

// *
// This section records information about under-construction files for
// reconstructing the lease map.
// NAME: FILES_UNDERCONSTRUCTION
type FilesUnderConstructionSection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesUnderConstructionSection) Reset() {
	*x = FilesUnderConstructionSection{}
	mi := &file_fsimage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesUnderConstructionSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesUnderConstructionSection) ProtoMessage() {}

func (x *FilesUnderConstructionSection) ProtoReflect() protoreflect.Message {
	mi := &file_fsimage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesUnderConstructionSection.ProtoReflect.Descriptor instead.
func (*FilesUnderConstructionSection) Descriptor() ([]byte, []int) {
	return file_fsimage_proto_rawDescGZIP(), []int{3}
}

// *
// This section records the children of each directories
// NAME: INODE_DIR
type INodeDirectorySection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *INodeDirectorySection) Reset() {
	*x = INodeDirectorySection{}
	mi := &file_fsimage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *INodeDirectorySection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*INodeDirectorySection) ProtoMessage() {}

func (x *INodeDirectorySection) ProtoReflect() protoreflect.Message {
	mi := &file_fsimage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use INodeDirectorySection.ProtoReflect.Descriptor instead.
func (*INodeDirectorySection) Descriptor() ([]byte, []int) {
	return file_fsimage_proto_rawDescGZIP(), []int{4}
}

type INodeReferenceSection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *INodeReferenceSection) Reset() {
	*x = INodeReferenceSection{}
	mi := &file_fsimage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *INodeReferenceSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*INodeReferenceSection) ProtoMessage() {}

func (x *INodeReferenceSection) ProtoReflect() protoreflect.Message {
	mi := &file_fsimage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use INodeReferenceSection.ProtoReflect.Descriptor instead.
func (*INodeReferenceSection) Descriptor() ([]byte, []int) {
	return file_fsimage_proto_rawDescGZIP(), []int{5}
}

// *
// This section records the information about snapshot
// NAME: SNAPSHOT
type SnapshotSection struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SnapshotCounter  *uint32                `protobuf:"varint,1,opt,name=snapshotCounter" json:"snapshotCounter,omitempty"`
	SnapshottableDir []uint64               `protobuf:"varint,2,rep,packed,name=snapshottableDir" json:"snapshottableDir,omitempty"`
	// total number of snapshots
	NumSnapshots  *uint32 `protobuf:"varint,3,opt,name=numSnapshots" json:"numSnapshots,omitempty"` // repeated Snapshot...
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotSection) Reset() {
	*x = SnapshotSection{}
	mi := &file_fsimage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotSection) ProtoMessage() {}

func (x *SnapshotSection) ProtoReflect() protoreflect.Message {
	mi := &file_fsimage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotSection.ProtoReflect.Descriptor instead.
func (*SnapshotSection) Descriptor() ([]byte, []int) {
	return file_fsimage_proto_rawDescGZIP(), []int{6}
}

func (x *SnapshotSection) GetSnapshotCounter() uint32 {
	if x != nil && x.SnapshotCounter != nil {
		return *x.SnapshotCounter
	}
	return 0
}

func (x *SnapshotSection) GetSnapshottableDir() []uint64 {
	if x != nil {
		return x.SnapshottableDir
	}
	return nil
}

func (x *SnapshotSection) GetNumSnapshots() uint32 {
	if x != nil && x.NumSnapshots != nil {
		return *x.NumSnapshots
	}
	return 0
}

// *
// This section records information about snapshot diffs
// NAME: SNAPSHOT_DIFF
type SnapshotDiffSection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotDiffSection) Reset() {
	*x = SnapshotDiffSection{}
	mi := &file_fsimage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotDiffSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotDiffSection) ProtoMessage() {}

func (x *SnapshotDiffSection) ProtoReflect() protoreflect.Message {
	mi := &file_fsimage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotDiffSection.ProtoReflect.Descriptor instead.
func (*SnapshotDiffSection) Descriptor() ([]byte, []int) {
	return file_fsimage_proto_rawDescGZIP(), []int{7}
}

// *
// This section maps string to id
// NAME: STRING_TABLE
type StringTableSection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumEntry      *uint32                `protobuf:"varint,1,opt,name=numEntry" json:"numEntry,omitempty"`
	MaskBits      *uint32                `protobuf:"varint,2,opt,name=maskBits,def=0" json:"maskBits,omitempty"` // repeated Entry
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for StringTableSection fields.
const (
	Default_StringTableSection_MaskBits = uint32(0)
)

func (x *StringTableSection) Reset() {
	*x = StringTableSection{}
	mi := &file_fsimage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringTableSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringTableSection) ProtoMessage() {}

func (x *StringTableSection) ProtoReflect() protoreflect.Message {
	mi := &file_fsimage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringTableSection.ProtoReflect.Descriptor instead.
func (*StringTableSection) Descriptor() ([]byte, []int) {
	return file_fsimage_proto_rawDescGZIP(), []int{8}
}

func (x *StringTableSection) GetNumEntry() uint32 {
	if x != nil && x.NumEntry != nil {
		return *x.NumEntry
	}
	return 0
}

func (x *StringTableSection) GetMaskBits() uint32 {
	if x != nil && x.MaskBits != nil {
		return *x.MaskBits
	}
	return Default_StringTableSection_MaskBits
}

type SecretManagerSection struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CurrentId           *uint32                `protobuf:"varint,1,opt,name=currentId" json:"currentId,omitempty"`
	TokenSequenceNumber *uint32                `protobuf:"varint,2,opt,name=tokenSequenceNumber" json:"tokenSequenceNumber,omitempty"`
	NumKeys             *uint32                `protobuf:"varint,3,opt,name=numKeys" json:"numKeys,omitempty"`
	NumTokens           *uint32                `protobuf:"varint,4,opt,name=numTokens" json:"numTokens,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SecretManagerSection) Reset() {
	*x = SecretManagerSection{}
	mi := &file_fsimage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretManagerSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretManagerSection) ProtoMessage() {}

func (x *SecretManagerSection) ProtoReflect() protoreflect.Message {
	mi := &file_fsimage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretManagerSection.ProtoReflect.Descriptor instead.
func (*SecretManagerSection) Descriptor() ([]byte, []int) {
	return file_fsimage_proto_rawDescGZIP(), []int{9}
}

func (x *SecretManagerSection) GetCurrentId() uint32 {
	if x != nil && x.CurrentId != nil {
		return *x.CurrentId
	}
	return 0
}

func (x *SecretManagerSection) GetTokenSequenceNumber() uint32 {
	if x != nil && x.TokenSequenceNumber != nil {
		return *x.TokenSequenceNumber
	}
	return 0
}

func (x *SecretManagerSection) GetNumKeys() uint32 {
	if x != nil && x.NumKeys != nil {
		return *x.NumKeys
	}
	return 0
}

func (x *SecretManagerSection) GetNumTokens() uint32 {
	if x != nil && x.NumTokens != nil {
		return *x.NumTokens
	}
	return 0
}

type CacheManagerSection struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NextDirectiveId *uint64                `protobuf:"varint,1,req,name=nextDirectiveId" json:"nextDirectiveId,omitempty"`
	NumPools        *uint32                `protobuf:"varint,2,req,name=numPools" json:"numPools,omitempty"`
	NumDirectives   *uint32                `protobuf:"varint,3,req,name=numDirectives" json:"numDirectives,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CacheManagerSection) Reset() {
	*x = CacheManagerSection{}
	mi := &file_fsimage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheManagerSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheManagerSection) ProtoMessage() {}

func (x *CacheManagerSection) ProtoReflect() protoreflect.Message {
	mi := &file_fsimage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheManagerSection.ProtoReflect.Descriptor instead.
func (*CacheManagerSection) Descriptor() ([]byte, []int) {
	return file_fsimage_proto_rawDescGZIP(), []int{10}
}

func (x *CacheManagerSection) GetNextDirectiveId() uint64 {
	if x != nil && x.NextDirectiveId != nil {
		return *x.NextDirectiveId
	}
	return 0
}

func (x *CacheManagerSection) GetNumPools() uint32 {
	if x != nil && x.NumPools != nil {
		return *x.NumPools
	}
	return 0
}

func (x *CacheManagerSection) GetNumDirectives() uint32 {
	if x != nil && x.NumDirectives != nil {
		return *x.NumDirectives
	}
	return 0
}

type ErasureCodingSection struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Policies      []*ErasureCodingPolicyProto `protobuf:"bytes,1,rep,name=policies" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErasureCodingSection) Reset() {
	*x = ErasureCodingSection{}
	mi := &file_fsimage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErasureCodingSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErasureCodingSection) ProtoMessage() {}

func (x *ErasureCodingSection) ProtoReflect() protoreflect.Message {
	mi := &file_fsimage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErasureCodingSection.ProtoReflect.Descriptor instead.
func (*ErasureCodingSection) Descriptor() ([]byte, []int) {
	return file_fsimage_proto_rawDescGZIP(), []int{11}
}

func (x *ErasureCodingSection) GetPolicies() []*ErasureCodingPolicyProto {
	if x != nil {
		return x.Policies
	}
	return nil
}

// index for each section
type FileSummary_Section struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Length        *uint64                `protobuf:"varint,2,opt,name=length" json:"length,omitempty"`
	Offset        *uint64                `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileSummary_Section) Reset() {
	*x = FileSummary_Section{}
	mi := &file_fsimage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileSummary_Section) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSummary_Section) ProtoMessage() {}

func (x *FileSummary_Section) ProtoReflect() protoreflect.Message {
	mi := &file_fsimage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSummary_Section.ProtoReflect.Descriptor instead.
func (*FileSummary_Section) Descriptor() ([]byte, []int) {
	return file_fsimage_proto_rawDescGZIP(), []int{0, 0}
}

func (x *FileSummary_Section) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *FileSummary_Section) GetLength() uint64 {
	if x != nil && x.Length != nil {
		return *x.Length
	}
	return 0
}

func (x *FileSummary_Section) GetOffset() uint64 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

// *
// under-construction feature for INodeFile
type INodeSection_FileUnderConstructionFeature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientName    *string                `protobuf:"bytes,1,opt,name=clientName" json:"clientName,omitempty"`
	ClientMachine *string                `protobuf:"bytes,2,opt,name=clientMachine" json:"clientMachine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *INodeSection_FileUnderConstructionFeature) Reset() {
	*x = INodeSection_FileUnderConstructionFeature{}
	mi := &file_fsimage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *INodeSection_FileUnderConstructionFeature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*INodeSection_FileUnderConstructionFeature) ProtoMessage() {}

func (x *INodeSection_FileUnderConstructionFeature) ProtoReflect() protoreflect.Message {
	mi := &file_fsimage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use INodeSection_FileUnderConstructionFeature.ProtoReflect.Descriptor instead.
func (*INodeSection_FileUnderConstructionFeature) Descriptor() ([]byte, []int) {
	return file_fsimage_proto_rawDescGZIP(), []int{2, 0}
}

func (x *INodeSection_FileUnderConstructionFeature) GetClientName() string {
	if x != nil && x.ClientName != nil {
		return *x.ClientName
	}
	return ""
}

func (x *INodeSection_FileUnderConstructionFeature) GetClientMachine() string {
	if x != nil && x.ClientMachine != nil {
		return *x.ClientMachine
	}
	return ""
}

type INodeSection_AclFeatureProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// An ACL entry is represented by a 32-bit integer in Big Endian
	// format. The bits can be divided in four segments:
	// [0:2) || [2:26) || [26:27) || [27:29) || [29:32)
	//
	// [0:2) -- reserved for futute uses.
	// [2:26) -- the name of the entry, which is an ID that points to a
	// string in the StringTableSection.
	// [26:27) -- the scope of the entry (AclEntryScopeProto)
	// [27:29) -- the type of the entry (AclEntryTypeProto)
	// [29:32) -- the permission of the entry (FsActionProto)
	Entries       []uint32 `protobuf:"fixed32,2,rep,packed,name=entries" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *INodeSection_AclFeatureProto) Reset() {
	*x = INodeSection_AclFeatureProto{}
	mi := &file_fsimage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *INodeSection_AclFeatureProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*INodeSection_AclFeatureProto) ProtoMessage() {}

func (x *INodeSection_AclFeatureProto) ProtoReflect() protoreflect.Message {
	mi := &file_fsimage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use INodeSection_AclFeatureProto.ProtoReflect.Descriptor instead.
func (*INodeSection_AclFeatureProto) Descriptor() ([]byte, []int) {
	return file_fsimage_proto_rawDescGZIP(), []int{2, 1}
}

func (x *INodeSection_AclFeatureProto) GetEntries() []uint32 {
	if x != nil {
		return x.Entries
	}
	return nil
}

type INodeSection_XAttrCompactProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	//
	// [0:2) -- the namespace of XAttr (XAttrNamespaceProto)
	// [2:26) -- the name of the entry, which is an ID that points to a
	// string in the StringTableSection.
	// [26:27) -- namespace extension. Originally there were only 4 namespaces
	// so only 2 bits were needed. At that time, this bit was reserved. When a
	// 5th namespace was created (raw) this bit became used as a 3rd namespace
	// bit.
	// [27:32) -- reserved for future uses.
	Name          *uint32 `protobuf:"fixed32,1,req,name=name" json:"name,omitempty"`
	Value         []byte  `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *INodeSection_XAttrCompactProto) Reset() {
	*x = INodeSection_XAttrCompactProto{}
	mi := &file_fsimage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *INodeSection_XAttrCompactProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*INodeSection_XAttrCompactProto) ProtoMessage() {}

func (x *INodeSection_XAttrCompactProto) ProtoReflect() protoreflect.Message {
	mi := &file_fsimage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use INodeSection_XAttrCompactProto.ProtoReflect.Descriptor instead.
func (*INodeSection_XAttrCompactProto) Descriptor() ([]byte, []int) {
	return file_fsimage_proto_rawDescGZIP(), []int{2, 2}
}

func (x *INodeSection_XAttrCompactProto) GetName() uint32 {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return 0
}

func (x *INodeSection_XAttrCompactProto) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type INodeSection_XAttrFeatureProto struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	XAttrs        []*INodeSection_XAttrCompactProto `protobuf:"bytes,1,rep,name=xAttrs" json:"xAttrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *INodeSection_XAttrFeatureProto) Reset() {
	*x = INodeSection_XAttrFeatureProto{}
	mi := &file_fsimage_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *INodeSection_XAttrFeatureProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*INodeSection_XAttrFeatureProto) ProtoMessage() {}

func (x *INodeSection_XAttrFeatureProto) ProtoReflect() protoreflect.Message {
	mi := &file_fsimage_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use INodeSection_XAttrFeatureProto.ProtoReflect.Descriptor instead.
func (*INodeSection_XAttrFeatureProto) Descriptor() ([]byte, []int) {
	return file_fsimage_proto_rawDescGZIP(), []int{2, 3}
}

func (x *INodeSection_XAttrFeatureProto) GetXAttrs() []*INodeSection_XAttrCompactProto {
	if x != nil {
		return x.XAttrs
	}
	return nil
}

type INodeSection_INodeFile struct {
	state                 protoimpl.MessageState                     `protogen:"open.v1"`
	Replication           *uint32                                    `protobuf:"varint,1,opt,name=replication" json:"replication,omitempty"`
	ModificationTime      *uint64                                    `protobuf:"varint,2,opt,name=modificationTime" json:"modificationTime,omitempty"`
	AccessTime            *uint64                                    `protobuf:"varint,3,opt,name=accessTime" json:"accessTime,omitempty"`
	PreferredBlockSize    *uint64                                    `protobuf:"varint,4,opt,name=preferredBlockSize" json:"preferredBlockSize,omitempty"`
	Permission            *uint64                                    `protobuf:"fixed64,5,opt,name=permission" json:"permission,omitempty"`
	Blocks                []*BlockProto                              `protobuf:"bytes,6,rep,name=blocks" json:"blocks,omitempty"`
	FileUC                *INodeSection_FileUnderConstructionFeature `protobuf:"bytes,7,opt,name=fileUC" json:"fileUC,omitempty"`
	Acl                   *INodeSection_AclFeatureProto              `protobuf:"bytes,8,opt,name=acl" json:"acl,omitempty"`
	XAttrs                *INodeSection_XAttrFeatureProto            `protobuf:"bytes,9,opt,name=xAttrs" json:"xAttrs,omitempty"`
	StoragePolicyID       *uint32                                    `protobuf:"varint,10,opt,name=storagePolicyID" json:"storagePolicyID,omitempty"`
	BlockType             *BlockTypeProto                            `protobuf:"varint,11,opt,name=blockType,enum=hadoop.hdfs.BlockTypeProto" json:"blockType,omitempty"`
	ErasureCodingPolicyID *uint32                                    `protobuf:"varint,12,opt,name=erasureCodingPolicyID" json:"erasureCodingPolicyID,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *INodeSection_INodeFile) Reset() {
	*x = INodeSection_INodeFile{}
	mi := &file_fsimage_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *INodeSection_INodeFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*INodeSection_INodeFile) ProtoMessage() {}

func (x *INodeSection_INodeFile) ProtoReflect() protoreflect.Message {
	mi := &file_fsimage_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use INodeSection_INodeFile.ProtoReflect.Descriptor instead.
func (*INodeSection_INodeFile) Descriptor() ([]byte, []int) {
	return file_fsimage_proto_rawDescGZIP(), []int{2, 4}
}

func (x *INodeSection_INodeFile) GetReplication() uint32 {
	if x != nil && x.Replication != nil {
		return *x.Replication
	}
	return 0
}

func (x *INodeSection_INodeFile) GetModificationTime() uint64 {
	if x != nil && x.ModificationTime != nil {
		return *x.ModificationTime
	}
	return 0
}

func (x *INodeSection_INodeFile) GetAccessTime() uint64 {
	if x != nil && x.AccessTime != nil {
		return *x.AccessTime
	}
	return 0
}

func (x *INodeSection_INodeFile) GetPreferredBlockSize() uint64 {
	if x != nil && x.PreferredBlockSize != nil {
		return *x.PreferredBlockSize
	}
	return 0
}

func (x *INodeSection_INodeFile) GetPermission() uint64 {
	if x != nil && x.Permission != nil {
		return *x.Permission
	}
	return 0
}

func (x *INodeSection_INodeFile) GetBlocks() []*BlockProto {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *INodeSection_INodeFile) GetFileUC() *INodeSection_FileUnderConstructionFeature {
	if x != nil {
		return x.FileUC
	}
	return nil
}

func (x *INodeSection_INodeFile) GetAcl() *INodeSection_AclFeatureProto {
	if x != nil {
		return x.Acl
	}
	return nil
}

func (x *INodeSection_INodeFile) GetXAttrs() *INodeSection_XAttrFeatureProto {
	if x != nil {
		return x.XAttrs
	}
	return nil
}

func (x *INodeSection_INodeFile) GetStoragePolicyID() uint32 {
	if x != nil && x.StoragePolicyID != nil {
		return *x.StoragePolicyID
	}
	return 0
}

func (x *INodeSection_INodeFile) GetBlockType() BlockTypeProto {
	if x != nil && x.BlockType != nil {
		return *x.BlockType
	}
	return BlockTypeProto_CONTIGUOUS
}

func (x *INodeSection_INodeFile) GetErasureCodingPolicyID() uint32 {
	if x != nil && x.ErasureCodingPolicyID != nil {
		return *x.ErasureCodingPolicyID
	}
	return 0
}

type INodeSection_QuotaByStorageTypeEntryProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StorageType   *StorageTypeProto      `protobuf:"varint,1,req,name=storageType,enum=hadoop.hdfs.StorageTypeProto" json:"storageType,omitempty"`
	Quota         *uint64                `protobuf:"varint,2,req,name=quota" json:"quota,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *INodeSection_QuotaByStorageTypeEntryProto) Reset() {
	*x = INodeSection_QuotaByStorageTypeEntryProto{}
	mi := &file_fsimage_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *INodeSection_QuotaByStorageTypeEntryProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*INodeSection_QuotaByStorageTypeEntryProto) ProtoMessage() {}

func (x *INodeSection_QuotaByStorageTypeEntryProto) ProtoReflect() protoreflect.Message {
	mi := &file_fsimage_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use INodeSection_QuotaByStorageTypeEntryProto.ProtoReflect.Descriptor instead.
func (*INodeSection_QuotaByStorageTypeEntryProto) Descriptor() ([]byte, []int) {
	return file_fsimage_proto_rawDescGZIP(), []int{2, 5}
}

func (x *INodeSection_QuotaByStorageTypeEntryProto) GetStorageType() StorageTypeProto {
	if x != nil && x.StorageType != nil {
		return *x.StorageType
	}
	return StorageTypeProto_DISK
}

func (x *INodeSection_QuotaByStorageTypeEntryProto) GetQuota() uint64 {
	if x != nil && x.Quota != nil {
		return *x.Quota
	}
	return 0
}

type INodeSection_QuotaByStorageTypeFeatureProto struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	Quotas        []*INodeSection_QuotaByStorageTypeEntryProto `protobuf:"bytes,1,rep,name=quotas" json:"quotas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *INodeSection_QuotaByStorageTypeFeatureProto) Reset() {
	*x = INodeSection_QuotaByStorageTypeFeatureProto{}
	mi := &file_fsimage_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *INodeSection_QuotaByStorageTypeFeatureProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*INodeSection_QuotaByStorageTypeFeatureProto) ProtoMessage() {}

func (x *INodeSection_QuotaByStorageTypeFeatureProto) ProtoReflect() protoreflect.Message {
	mi := &file_fsimage_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use INodeSection_QuotaByStorageTypeFeatureProto.ProtoReflect.Descriptor instead.
func (*INodeSection_QuotaByStorageTypeFeatureProto) Descriptor() ([]byte, []int) {
	return file_fsimage_proto_rawDescGZIP(), []int{2, 6}
}

func (x *INodeSection_QuotaByStorageTypeFeatureProto) GetQuotas() []*INodeSection_QuotaByStorageTypeEntryProto {
	if x != nil {
		return x.Quotas
	}
	return nil
}

type INodeSection_INodeDirectory struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ModificationTime *uint64                `protobuf:"varint,1,opt,name=modificationTime" json:"modificationTime,omitempty"`
	// namespace quota
	NsQuota *uint64 `protobuf:"varint,2,opt,name=nsQuota" json:"nsQuota,omitempty"`
	// diskspace quota
	DsQuota       *uint64                                      `protobuf:"varint,3,opt,name=dsQuota" json:"dsQuota,omitempty"`
	Permission    *uint64                                      `protobuf:"fixed64,4,opt,name=permission" json:"permission,omitempty"`
	Acl           *INodeSection_AclFeatureProto                `protobuf:"bytes,5,opt,name=acl" json:"acl,omitempty"`
	XAttrs        *INodeSection_XAttrFeatureProto              `protobuf:"bytes,6,opt,name=xAttrs" json:"xAttrs,omitempty"`
	TypeQuotas    *INodeSection_QuotaByStorageTypeFeatureProto `protobuf:"bytes,7,opt,name=typeQuotas" json:"typeQuotas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *INodeSection_INodeDirectory) Reset() {
	*x = INodeSection_INodeDirectory{}
	mi := &file_fsimage_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *INodeSection_INodeDirectory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*INodeSection_INodeDirectory) ProtoMessage() {}

func (x *INodeSection_INodeDirectory) ProtoReflect() protoreflect.Message {
	mi := &file_fsimage_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use INodeSection_INodeDirectory.ProtoReflect.Descriptor instead.
func (*INodeSection_INodeDirectory) Descriptor() ([]byte, []int) {
	return file_fsimage_proto_rawDescGZIP(), []int{2, 7}
}

func (x *INodeSection_INodeDirectory) GetModificationTime() uint64 {
	if x != nil && x.ModificationTime != nil {
		return *x.ModificationTime
	}
	return 0
}

func (x *INodeSection_INodeDirectory) GetNsQuota() uint64 {
	if x != nil && x.NsQuota != nil {
		return *x.NsQuota
	}
	return 0
}

func (x *INodeSection_INodeDirectory) GetDsQuota() uint64 {
	if x != nil && x.DsQuota != nil {
		return *x.DsQuota
	}
	return 0
}

func (x *INodeSection_INodeDirectory) GetPermission() uint64 {
	if x != nil && x.Permission != nil {
		return *x.Permission
	}
	return 0
}

func (x *INodeSection_INodeDirectory) GetAcl() *INodeSection_AclFeatureProto {
	if x != nil {
		return x.Acl
	}
	return nil
}

func (x *INodeSection_INodeDirectory) GetXAttrs() *INodeSection_XAttrFeatureProto {
	if x != nil {
		return x.XAttrs
	}
	return nil
}

func (x *INodeSection_INodeDirectory) GetTypeQuotas() *INodeSection_QuotaByStorageTypeFeatureProto {
	if x != nil {
		return x.TypeQuotas
	}
	return nil
}

type INodeSection_INodeSymlink struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Permission       *uint64                `protobuf:"fixed64,1,opt,name=permission" json:"permission,omitempty"`
	Target           []byte                 `protobuf:"bytes,2,opt,name=target" json:"target,omitempty"`
	ModificationTime *uint64                `protobuf:"varint,3,opt,name=modificationTime" json:"modificationTime,omitempty"`
	AccessTime       *uint64                `protobuf:"varint,4,opt,name=accessTime" json:"accessTime,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *INodeSection_INodeSymlink) Reset() {
	*x = INodeSection_INodeSymlink{}
	mi := &file_fsimage_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *INodeSection_INodeSymlink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*INodeSection_INodeSymlink) ProtoMessage() {}

func (x *INodeSection_INodeSymlink) ProtoReflect() protoreflect.Message {
	mi := &file_fsimage_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use INodeSection_INodeSymlink.ProtoReflect.Descriptor instead.
func (*INodeSection_INodeSymlink) Descriptor() ([]byte, []int) {
	return file_fsimage_proto_rawDescGZIP(), []int{2, 8}
}

func (x *INodeSection_INodeSymlink) GetPermission() uint64 {
	if x != nil && x.Permission != nil {
		return *x.Permission
	}
	return 0
}

func (x *INodeSection_INodeSymlink) GetTarget() []byte {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *INodeSection_INodeSymlink) GetModificationTime() uint64 {
	if x != nil && x.ModificationTime != nil {
		return *x.ModificationTime
	}
	return 0
}

func (x *INodeSection_INodeSymlink) GetAccessTime() uint64 {
	if x != nil && x.AccessTime != nil {
		return *x.AccessTime
	}
	return 0
}

type INodeSection_INode struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Type          *INodeSection_INode_Type     `protobuf:"varint,1,req,name=type,enum=hadoop.hdfs.fsimage.INodeSection_INode_Type" json:"type,omitempty"`
	Id            *uint64                      `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	Name          []byte                       `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	File          *INodeSection_INodeFile      `protobuf:"bytes,4,opt,name=file" json:"file,omitempty"`
	Directory     *INodeSection_INodeDirectory `protobuf:"bytes,5,opt,name=directory" json:"directory,omitempty"`
	Symlink       *INodeSection_INodeSymlink   `protobuf:"bytes,6,opt,name=symlink" json:"symlink,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *INodeSection_INode) Reset() {
	*x = INodeSection_INode{}
	mi := &file_fsimage_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *INodeSection_INode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*INodeSection_INode) ProtoMessage() {}

func (x *INodeSection_INode) ProtoReflect() protoreflect.Message {
	mi := &file_fsimage_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use INodeSection_INode.ProtoReflect.Descriptor instead.
func (*INodeSection_INode) Descriptor() ([]byte, []int) {
	return file_fsimage_proto_rawDescGZIP(), []int{2, 9}
}

func (x *INodeSection_INode) GetType() INodeSection_INode_Type {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return INodeSection_INode_FILE
}

func (x *INodeSection_INode) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *INodeSection_INode) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *INodeSection_INode) GetFile() *INodeSection_INodeFile {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *INodeSection_INode) GetDirectory() *INodeSection_INodeDirectory {
	if x != nil {
		return x.Directory
	}
	return nil
}

func (x *INodeSection_INode) GetSymlink() *INodeSection_INodeSymlink {
	if x != nil {
		return x.Symlink
	}
	return nil
}

type FilesUnderConstructionSection_FileUnderConstructionEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InodeId       *uint64                `protobuf:"varint,1,opt,name=inodeId" json:"inodeId,omitempty"`
	FullPath      *string                `protobuf:"bytes,2,opt,name=fullPath" json:"fullPath,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesUnderConstructionSection_FileUnderConstructionEntry) Reset() {
	*x = FilesUnderConstructionSection_FileUnderConstructionEntry{}
	mi := &file_fsimage_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesUnderConstructionSection_FileUnderConstructionEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesUnderConstructionSection_FileUnderConstructionEntry) ProtoMessage() {}

func (x *FilesUnderConstructionSection_FileUnderConstructionEntry) ProtoReflect() protoreflect.Message {
	mi := &file_fsimage_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesUnderConstructionSection_FileUnderConstructionEntry.ProtoReflect.Descriptor instead.
func (*FilesUnderConstructionSection_FileUnderConstructionEntry) Descriptor() ([]byte, []int) {
	return file_fsimage_proto_rawDescGZIP(), []int{3, 0}
}

func (x *FilesUnderConstructionSection_FileUnderConstructionEntry) GetInodeId() uint64 {
	if x != nil && x.InodeId != nil {
		return *x.InodeId
	}
	return 0
}

func (x *FilesUnderConstructionSection_FileUnderConstructionEntry) GetFullPath() string {
	if x != nil && x.FullPath != nil {
		return *x.FullPath
	}
	return ""
}

// *
// A single DirEntry needs to fit in the default PB max message size of
// 64MB. Please be careful when adding more fields to a DirEntry!
type INodeDirectorySection_DirEntry struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Parent *uint64                `protobuf:"varint,1,opt,name=parent" json:"parent,omitempty"`
	// children that are not reference nodes
	Children []uint64 `protobuf:"varint,2,rep,packed,name=children" json:"children,omitempty"`
	// children that are reference nodes, each element is a reference node id
	RefChildren   []uint32 `protobuf:"varint,3,rep,packed,name=refChildren" json:"refChildren,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *INodeDirectorySection_DirEntry) Reset() {
	*x = INodeDirectorySection_DirEntry{}
	mi := &file_fsimage_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *INodeDirectorySection_DirEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*INodeDirectorySection_DirEntry) ProtoMessage() {}

func (x *INodeDirectorySection_DirEntry) ProtoReflect() protoreflect.Message {
	mi := &file_fsimage_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use INodeDirectorySection_DirEntry.ProtoReflect.Descriptor instead.
func (*INodeDirectorySection_DirEntry) Descriptor() ([]byte, []int) {
	return file_fsimage_proto_rawDescGZIP(), []int{4, 0}
}

func (x *INodeDirectorySection_DirEntry) GetParent() uint64 {
	if x != nil && x.Parent != nil {
		return *x.Parent
	}
	return 0
}

func (x *INodeDirectorySection_DirEntry) GetChildren() []uint64 {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *INodeDirectorySection_DirEntry) GetRefChildren() []uint32 {
	if x != nil {
		return x.RefChildren
	}
	return nil
}

type INodeReferenceSection_INodeReference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id of the referred inode
	ReferredId *uint64 `protobuf:"varint,1,opt,name=referredId" json:"referredId,omitempty"`
	// local name recorded in WithName
	Name []byte `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// recorded in DstReference
	DstSnapshotId *uint32 `protobuf:"varint,3,opt,name=dstSnapshotId" json:"dstSnapshotId,omitempty"`
	// recorded in WithName
	LastSnapshotId *uint32 `protobuf:"varint,4,opt,name=lastSnapshotId" json:"lastSnapshotId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *INodeReferenceSection_INodeReference) Reset() {
	*x = INodeReferenceSection_INodeReference{}
	mi := &file_fsimage_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *INodeReferenceSection_INodeReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*INodeReferenceSection_INodeReference) ProtoMessage() {}

func (x *INodeReferenceSection_INodeReference) ProtoReflect() protoreflect.Message {
	mi := &file_fsimage_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use INodeReferenceSection_INodeReference.ProtoReflect.Descriptor instead.
func (*INodeReferenceSection_INodeReference) Descriptor() ([]byte, []int) {
	return file_fsimage_proto_rawDescGZIP(), []int{5, 0}
}

func (x *INodeReferenceSection_INodeReference) GetReferredId() uint64 {
	if x != nil && x.ReferredId != nil {
		return *x.ReferredId
	}
	return 0
}

func (x *INodeReferenceSection_INodeReference) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *INodeReferenceSection_INodeReference) GetDstSnapshotId() uint32 {
	if x != nil && x.DstSnapshotId != nil {
		return *x.DstSnapshotId
	}
	return 0
}

func (x *INodeReferenceSection_INodeReference) GetLastSnapshotId() uint32 {
	if x != nil && x.LastSnapshotId != nil {
		return *x.LastSnapshotId
	}
	return 0
}

type SnapshotSection_Snapshot struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId *uint32                `protobuf:"varint,1,opt,name=snapshotId" json:"snapshotId,omitempty"`
	// Snapshot root
	Root          *INodeSection_INode `protobuf:"bytes,2,opt,name=root" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotSection_Snapshot) Reset() {
	*x = SnapshotSection_Snapshot{}
	mi := &file_fsimage_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotSection_Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotSection_Snapshot) ProtoMessage() {}

func (x *SnapshotSection_Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_fsimage_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotSection_Snapshot.ProtoReflect.Descriptor instead.
func (*SnapshotSection_Snapshot) Descriptor() ([]byte, []int) {
	return file_fsimage_proto_rawDescGZIP(), []int{6, 0}
}

func (x *SnapshotSection_Snapshot) GetSnapshotId() uint32 {
	if x != nil && x.SnapshotId != nil {
		return *x.SnapshotId
	}
	return 0
}

func (x *SnapshotSection_Snapshot) GetRoot() *INodeSection_INode {
	if x != nil {
		return x.Root
	}
	return nil
}

type SnapshotDiffSection_CreatedListEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          []byte                 `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotDiffSection_CreatedListEntry) Reset() {
	*x = SnapshotDiffSection_CreatedListEntry{}
	mi := &file_fsimage_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotDiffSection_CreatedListEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotDiffSection_CreatedListEntry) ProtoMessage() {}

func (x *SnapshotDiffSection_CreatedListEntry) ProtoReflect() protoreflect.Message {
	mi := &file_fsimage_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotDiffSection_CreatedListEntry.ProtoReflect.Descriptor instead.
func (*SnapshotDiffSection_CreatedListEntry) Descriptor() ([]byte, []int) {
	return file_fsimage_proto_rawDescGZIP(), []int{7, 0}
}

func (x *SnapshotDiffSection_CreatedListEntry) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

type SnapshotDiffSection_DirectoryDiff struct {
	state           protoimpl.MessageState       `protogen:"open.v1"`
	SnapshotId      *uint32                      `protobuf:"varint,1,opt,name=snapshotId" json:"snapshotId,omitempty"`
	ChildrenSize    *uint32                      `protobuf:"varint,2,opt,name=childrenSize" json:"childrenSize,omitempty"`
	IsSnapshotRoot  *bool                        `protobuf:"varint,3,opt,name=isSnapshotRoot" json:"isSnapshotRoot,omitempty"`
	Name            []byte                       `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	SnapshotCopy    *INodeSection_INodeDirectory `protobuf:"bytes,5,opt,name=snapshotCopy" json:"snapshotCopy,omitempty"`
	CreatedListSize *uint32                      `protobuf:"varint,6,opt,name=createdListSize" json:"createdListSize,omitempty"`
	DeletedINode    []uint64                     `protobuf:"varint,7,rep,packed,name=deletedINode" json:"deletedINode,omitempty"` // id of deleted inodes
	// id of reference nodes in the deleted list
	DeletedINodeRef []uint32 `protobuf:"varint,8,rep,packed,name=deletedINodeRef" json:"deletedINodeRef,omitempty"` // repeated CreatedListEntry (size is specified by createdListSize)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SnapshotDiffSection_DirectoryDiff) Reset() {
	*x = SnapshotDiffSection_DirectoryDiff{}
	mi := &file_fsimage_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotDiffSection_DirectoryDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotDiffSection_DirectoryDiff) ProtoMessage() {}

func (x *SnapshotDiffSection_DirectoryDiff) ProtoReflect() protoreflect.Message {
	mi := &file_fsimage_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotDiffSection_DirectoryDiff.ProtoReflect.Descriptor instead.
func (*SnapshotDiffSection_DirectoryDiff) Descriptor() ([]byte, []int) {
	return file_fsimage_proto_rawDescGZIP(), []int{7, 1}
}

func (x *SnapshotDiffSection_DirectoryDiff) GetSnapshotId() uint32 {
	if x != nil && x.SnapshotId != nil {
		return *x.SnapshotId
	}
	return 0
}

func (x *SnapshotDiffSection_DirectoryDiff) GetChildrenSize() uint32 {
	if x != nil && x.ChildrenSize != nil {
		return *x.ChildrenSize
	}
	return 0
}

func (x *SnapshotDiffSection_DirectoryDiff) GetIsSnapshotRoot() bool {
	if x != nil && x.IsSnapshotRoot != nil {
		return *x.IsSnapshotRoot
	}
	return false
}

func (x *SnapshotDiffSection_DirectoryDiff) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *SnapshotDiffSection_DirectoryDiff) GetSnapshotCopy() *INodeSection_INodeDirectory {
	if x != nil {
		return x.SnapshotCopy
	}
	return nil
}

func (x *SnapshotDiffSection_DirectoryDiff) GetCreatedListSize() uint32 {
	if x != nil && x.CreatedListSize != nil {
		return *x.CreatedListSize
	}
	return 0
}

func (x *SnapshotDiffSection_DirectoryDiff) GetDeletedINode() []uint64 {
	if x != nil {
		return x.DeletedINode
	}
	return nil
}

func (x *SnapshotDiffSection_DirectoryDiff) GetDeletedINodeRef() []uint32 {
	if x != nil {
		return x.DeletedINodeRef
	}
	return nil
}

type SnapshotDiffSection_FileDiff struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	SnapshotId    *uint32                 `protobuf:"varint,1,opt,name=snapshotId" json:"snapshotId,omitempty"`
	FileSize      *uint64                 `protobuf:"varint,2,opt,name=fileSize" json:"fileSize,omitempty"`
	Name          []byte                  `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	SnapshotCopy  *INodeSection_INodeFile `protobuf:"bytes,4,opt,name=snapshotCopy" json:"snapshotCopy,omitempty"`
	Blocks        []*BlockProto           `protobuf:"bytes,5,rep,name=blocks" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotDiffSection_FileDiff) Reset() {
	*x = SnapshotDiffSection_FileDiff{}
	mi := &file_fsimage_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotDiffSection_FileDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotDiffSection_FileDiff) ProtoMessage() {}

func (x *SnapshotDiffSection_FileDiff) ProtoReflect() protoreflect.Message {
	mi := &file_fsimage_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotDiffSection_FileDiff.ProtoReflect.Descriptor instead.
func (*SnapshotDiffSection_FileDiff) Descriptor() ([]byte, []int) {
	return file_fsimage_proto_rawDescGZIP(), []int{7, 2}
}

func (x *SnapshotDiffSection_FileDiff) GetSnapshotId() uint32 {
	if x != nil && x.SnapshotId != nil {
		return *x.SnapshotId
	}
	return 0
}

func (x *SnapshotDiffSection_FileDiff) GetFileSize() uint64 {
	if x != nil && x.FileSize != nil {
		return *x.FileSize
	}
	return 0
}

func (x *SnapshotDiffSection_FileDiff) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *SnapshotDiffSection_FileDiff) GetSnapshotCopy() *INodeSection_INodeFile {
	if x != nil {
		return x.SnapshotCopy
	}
	return nil
}

func (x *SnapshotDiffSection_FileDiff) GetBlocks() []*BlockProto {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type SnapshotDiffSection_DiffEntry struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Type          *SnapshotDiffSection_DiffEntry_Type `protobuf:"varint,1,req,name=type,enum=hadoop.hdfs.fsimage.SnapshotDiffSection_DiffEntry_Type" json:"type,omitempty"`
	InodeId       *uint64                             `protobuf:"varint,2,opt,name=inodeId" json:"inodeId,omitempty"`
	NumOfDiff     *uint32                             `protobuf:"varint,3,opt,name=numOfDiff" json:"numOfDiff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotDiffSection_DiffEntry) Reset() {
	*x = SnapshotDiffSection_DiffEntry{}
	mi := &file_fsimage_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotDiffSection_DiffEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotDiffSection_DiffEntry) ProtoMessage() {}

func (x *SnapshotDiffSection_DiffEntry) ProtoReflect() protoreflect.Message {
	mi := &file_fsimage_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotDiffSection_DiffEntry.ProtoReflect.Descriptor instead.
func (*SnapshotDiffSection_DiffEntry) Descriptor() ([]byte, []int) {
	return file_fsimage_proto_rawDescGZIP(), []int{7, 3}
}

func (x *SnapshotDiffSection_DiffEntry) GetType() SnapshotDiffSection_DiffEntry_Type {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return SnapshotDiffSection_DiffEntry_FILEDIFF
}

func (x *SnapshotDiffSection_DiffEntry) GetInodeId() uint64 {
	if x != nil && x.InodeId != nil {
		return *x.InodeId
	}
	return 0
}

func (x *SnapshotDiffSection_DiffEntry) GetNumOfDiff() uint32 {
	if x != nil && x.NumOfDiff != nil {
		return *x.NumOfDiff
	}
	return 0
}

type StringTableSection_Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Str           *string                `protobuf:"bytes,2,opt,name=str" json:"str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringTableSection_Entry) Reset() {
	*x = StringTableSection_Entry{}
	mi := &file_fsimage_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringTableSection_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringTableSection_Entry) ProtoMessage() {}

func (x *StringTableSection_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_fsimage_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringTableSection_Entry.ProtoReflect.Descriptor instead.
func (*StringTableSection_Entry) Descriptor() ([]byte, []int) {
	return file_fsimage_proto_rawDescGZIP(), []int{8, 0}
}

func (x *StringTableSection_Entry) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *StringTableSection_Entry) GetStr() string {
	if x != nil && x.Str != nil {
		return *x.Str
	}
	return ""
}

type SecretManagerSection_DelegationKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	ExpiryDate    *uint64                `protobuf:"varint,2,opt,name=expiryDate" json:"expiryDate,omitempty"`
	Key           []byte                 `protobuf:"bytes,3,opt,name=key" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretManagerSection_DelegationKey) Reset() {
	*x = SecretManagerSection_DelegationKey{}
	mi := &file_fsimage_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretManagerSection_DelegationKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretManagerSection_DelegationKey) ProtoMessage() {}

func (x *SecretManagerSection_DelegationKey) ProtoReflect() protoreflect.Message {
	mi := &file_fsimage_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretManagerSection_DelegationKey.ProtoReflect.Descriptor instead.
func (*SecretManagerSection_DelegationKey) Descriptor() ([]byte, []int) {
	return file_fsimage_proto_rawDescGZIP(), []int{9, 0}
}

func (x *SecretManagerSection_DelegationKey) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *SecretManagerSection_DelegationKey) GetExpiryDate() uint64 {
	if x != nil && x.ExpiryDate != nil {
		return *x.ExpiryDate
	}
	return 0
}

func (x *SecretManagerSection_DelegationKey) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type SecretManagerSection_PersistToken struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Version        *uint32                `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Owner          *string                `protobuf:"bytes,2,opt,name=owner" json:"owner,omitempty"`
	Renewer        *string                `protobuf:"bytes,3,opt,name=renewer" json:"renewer,omitempty"`
	RealUser       *string                `protobuf:"bytes,4,opt,name=realUser" json:"realUser,omitempty"`
	IssueDate      *uint64                `protobuf:"varint,5,opt,name=issueDate" json:"issueDate,omitempty"`
	MaxDate        *uint64                `protobuf:"varint,6,opt,name=maxDate" json:"maxDate,omitempty"`
	SequenceNumber *uint32                `protobuf:"varint,7,opt,name=sequenceNumber" json:"sequenceNumber,omitempty"`
	MasterKeyId    *uint32                `protobuf:"varint,8,opt,name=masterKeyId" json:"masterKeyId,omitempty"`
	ExpiryDate     *uint64                `protobuf:"varint,9,opt,name=expiryDate" json:"expiryDate,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SecretManagerSection_PersistToken) Reset() {
	*x = SecretManagerSection_PersistToken{}
	mi := &file_fsimage_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretManagerSection_PersistToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretManagerSection_PersistToken) ProtoMessage() {}

func (x *SecretManagerSection_PersistToken) ProtoReflect() protoreflect.Message {
	mi := &file_fsimage_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretManagerSection_PersistToken.ProtoReflect.Descriptor instead.
func (*SecretManagerSection_PersistToken) Descriptor() ([]byte, []int) {
	return file_fsimage_proto_rawDescGZIP(), []int{9, 1}
}

func (x *SecretManagerSection_PersistToken) GetVersion() uint32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *SecretManagerSection_PersistToken) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

func (x *SecretManagerSection_PersistToken) GetRenewer() string {
	if x != nil && x.Renewer != nil {
		return *x.Renewer
	}
	return ""
}

func (x *SecretManagerSection_PersistToken) GetRealUser() string {
	if x != nil && x.RealUser != nil {
		return *x.RealUser
	}
	return ""
}

func (x *SecretManagerSection_PersistToken) GetIssueDate() uint64 {
	if x != nil && x.IssueDate != nil {
		return *x.IssueDate
	}
	return 0
}

func (x *SecretManagerSection_PersistToken) GetMaxDate() uint64 {
	if x != nil && x.MaxDate != nil {
		return *x.MaxDate
	}
	return 0
}

func (x *SecretManagerSection_PersistToken) GetSequenceNumber() uint32 {
	if x != nil && x.SequenceNumber != nil {
		return *x.SequenceNumber
	}
	return 0
}

func (x *SecretManagerSection_PersistToken) GetMasterKeyId() uint32 {
	if x != nil && x.MasterKeyId != nil {
		return *x.MasterKeyId
	}
	return 0
}

func (x *SecretManagerSection_PersistToken) GetExpiryDate() uint64 {
	if x != nil && x.ExpiryDate != nil {
		return *x.ExpiryDate
	}
	return 0
}

var File_fsimage_proto protoreflect.FileDescriptor

const file_fsimage_proto_rawDesc = "" +
	"\n" +
	"\rfsimage.proto\x12\x13hadoop.hdfs.fsimage\x1a\n" +
	"hdfs.proto\x1a\tacl.proto\x1a\vxattr.proto\"\x84\x02\n" +
	"\vFileSummary\x12$\n" +
	"\rondiskVersion\x18\x01 \x02(\rR\rondiskVersion\x12$\n" +
	"\rlayoutVersion\x18\x02 \x02(\rR\rlayoutVersion\x12\x14\n" +
	"\x05codec\x18\x03 \x01(\tR\x05codec\x12D\n" +
	"\bsections\x18\x04 \x03(\v2(.hadoop.hdfs.fsimage.FileSummary.SectionR\bsections\x1aM\n" +
	"\aSection\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x04R\x06length\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\"\xf5\x02\n" +
	"\x11NameSystemSection\x12 \n" +
	"\vnamespaceId\x18\x01 \x01(\rR\vnamespaceId\x12\x1e\n" +
	"\n" +
	"genstampV1\x18\x02 \x01(\x04R\n" +
	"genstampV1\x12\x1e\n" +
	"\n" +
	"genstampV2\x18\x03 \x01(\x04R\n" +
	"genstampV2\x12(\n" +
	"\x0fgenstampV1Limit\x18\x04 \x01(\x04R\x0fgenstampV1Limit\x122\n" +
	"\x14lastAllocatedBlockId\x18\x05 \x01(\x04R\x14lastAllocatedBlockId\x12$\n" +
	"\rtransactionId\x18\x06 \x01(\x04R\rtransactionId\x128\n" +
	"\x17rollingUpgradeStartTime\x18\a \x01(\x04R\x17rollingUpgradeStartTime\x12@\n" +
	"\x1blastAllocatedStripedBlockId\x18\b \x01(\x04R\x1blastAllocatedStripedBlockId\"\x8e\x11\n" +
	"\fINodeSection\x12 \n" +
	"\vlastInodeId\x18\x01 \x01(\x04R\vlastInodeId\x12\x1c\n" +
	"\tnumInodes\x18\x02 \x01(\x04R\tnumInodes\x1ad\n" +
	"\x1cFileUnderConstructionFeature\x12\x1e\n" +
	"\n" +
	"clientName\x18\x01 \x01(\tR\n" +
	"clientName\x12$\n" +
	"\rclientMachine\x18\x02 \x01(\tR\rclientMachine\x1a/\n" +
	"\x0fAclFeatureProto\x12\x1c\n" +
	"\aentries\x18\x02 \x03(\aB\x02\x10\x01R\aentries\x1a=\n" +
	"\x11XAttrCompactProto\x12\x12\n" +
	"\x04name\x18\x01 \x02(\aR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x1a`\n" +
	"\x11XAttrFeatureProto\x12K\n" +
	"\x06xAttrs\x18\x01 \x03(\v23.hadoop.hdfs.fsimage.INodeSection.XAttrCompactProtoR\x06xAttrs\x1a\xff\x04\n" +
	"\tINodeFile\x12 \n" +
	"\vreplication\x18\x01 \x01(\rR\vreplication\x12*\n" +
	"\x10modificationTime\x18\x02 \x01(\x04R\x10modificationTime\x12\x1e\n" +
	"\n" +
	"accessTime\x18\x03 \x01(\x04R\n" +
	"accessTime\x12.\n" +
	"\x12preferredBlockSize\x18\x04 \x01(\x04R\x12preferredBlockSize\x12\x1e\n" +
	"\n" +
	"permission\x18\x05 \x01(\x06R\n" +
	"permission\x12/\n" +
	"\x06blocks\x18\x06 \x03(\v2\x17.hadoop.hdfs.BlockProtoR\x06blocks\x12V\n" +
	"\x06fileUC\x18\a \x01(\v2>.hadoop.hdfs.fsimage.INodeSection.FileUnderConstructionFeatureR\x06fileUC\x12C\n" +
	"\x03acl\x18\b \x01(\v21.hadoop.hdfs.fsimage.INodeSection.AclFeatureProtoR\x03acl\x12K\n" +
	"\x06xAttrs\x18\t \x01(\v23.hadoop.hdfs.fsimage.INodeSection.XAttrFeatureProtoR\x06xAttrs\x12(\n" +
	"\x0fstoragePolicyID\x18\n" +
	" \x01(\rR\x0fstoragePolicyID\x129\n" +
	"\tblockType\x18\v \x01(\x0e2\x1b.hadoop.hdfs.BlockTypeProtoR\tblockType\x124\n" +
	"\x15erasureCodingPolicyID\x18\f \x01(\rR\x15erasureCodingPolicyID\x1au\n" +
	"\x1cQuotaByStorageTypeEntryProto\x12?\n" +
	"\vstorageType\x18\x01 \x02(\x0e2\x1d.hadoop.hdfs.StorageTypeProtoR\vstorageType\x12\x14\n" +
	"\x05quota\x18\x02 \x02(\x04R\x05quota\x1ax\n" +
	"\x1eQuotaByStorageTypeFeatureProto\x12V\n" +
	"\x06quotas\x18\x01 \x03(\v2>.hadoop.hdfs.fsimage.INodeSection.QuotaByStorageTypeEntryProtoR\x06quotas\x1a\x84\x03\n" +
	"\x0eINodeDirectory\x12*\n" +
	"\x10modificationTime\x18\x01 \x01(\x04R\x10modificationTime\x12\x18\n" +
	"\ansQuota\x18\x02 \x01(\x04R\ansQuota\x12\x18\n" +
	"\adsQuota\x18\x03 \x01(\x04R\adsQuota\x12\x1e\n" +
	"\n" +
	"permission\x18\x04 \x01(\x06R\n" +
	"permission\x12C\n" +
	"\x03acl\x18\x05 \x01(\v21.hadoop.hdfs.fsimage.INodeSection.AclFeatureProtoR\x03acl\x12K\n" +
	"\x06xAttrs\x18\x06 \x01(\v23.hadoop.hdfs.fsimage.INodeSection.XAttrFeatureProtoR\x06xAttrs\x12`\n" +
	"\n" +
	"typeQuotas\x18\a \x01(\v2@.hadoop.hdfs.fsimage.INodeSection.QuotaByStorageTypeFeatureProtoR\n" +
	"typeQuotas\x1a\x92\x01\n" +
	"\fINodeSymlink\x12\x1e\n" +
	"\n" +
	"permission\x18\x01 \x01(\x06R\n" +
	"permission\x12\x16\n" +
	"\x06target\x18\x02 \x01(\fR\x06target\x12*\n" +
	"\x10modificationTime\x18\x03 \x01(\x04R\x10modificationTime\x12\x1e\n" +
	"\n" +
	"accessTime\x18\x04 \x01(\x04R\n" +
	"accessTime\x1a\xf6\x02\n" +
	"\x05INode\x12@\n" +
	"\x04type\x18\x01 \x02(\x0e2,.hadoop.hdfs.fsimage.INodeSection.INode.TypeR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x02(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\fR\x04name\x12?\n" +
	"\x04file\x18\x04 \x01(\v2+.hadoop.hdfs.fsimage.INodeSection.INodeFileR\x04file\x12N\n" +
	"\tdirectory\x18\x05 \x01(\v20.hadoop.hdfs.fsimage.INodeSection.INodeDirectoryR\tdirectory\x12H\n" +
	"\asymlink\x18\x06 \x01(\v2..hadoop.hdfs.fsimage.INodeSection.INodeSymlinkR\asymlink\",\n" +
	"\x04Type\x12\b\n" +
	"\x04FILE\x10\x01\x12\r\n" +
	"\tDIRECTORY\x10\x02\x12\v\n" +
	"\aSYMLINK\x10\x03\"s\n" +
	"\x1dFilesUnderConstructionSection\x1aR\n" +
	"\x1aFileUnderConstructionEntry\x12\x18\n" +
	"\ainodeId\x18\x01 \x01(\x04R\ainodeId\x12\x1a\n" +
	"\bfullPath\x18\x02 \x01(\tR\bfullPath\"\x81\x01\n" +
	"\x15INodeDirectorySection\x1ah\n" +
	"\bDirEntry\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\x04R\x06parent\x12\x1e\n" +
	"\bchildren\x18\x02 \x03(\x04B\x02\x10\x01R\bchildren\x12$\n" +
	"\vrefChildren\x18\x03 \x03(\rB\x02\x10\x01R\vrefChildren\"\xac\x01\n" +
	"\x15INodeReferenceSection\x1a\x92\x01\n" +
	"\x0eINodeReference\x12\x1e\n" +
	"\n" +
	"referredId\x18\x01 \x01(\x04R\n" +
	"referredId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\fR\x04name\x12$\n" +
	"\rdstSnapshotId\x18\x03 \x01(\rR\rdstSnapshotId\x12&\n" +
	"\x0elastSnapshotId\x18\x04 \x01(\rR\x0elastSnapshotId\"\xf8\x01\n" +
	"\x0fSnapshotSection\x12(\n" +
	"\x0fsnapshotCounter\x18\x01 \x01(\rR\x0fsnapshotCounter\x12.\n" +
	"\x10snapshottableDir\x18\x02 \x03(\x04B\x02\x10\x01R\x10snapshottableDir\x12\"\n" +
	"\fnumSnapshots\x18\x03 \x01(\rR\fnumSnapshots\x1ag\n" +
	"\bSnapshot\x12\x1e\n" +
	"\n" +
	"snapshotId\x18\x01 \x01(\rR\n" +
	"snapshotId\x12;\n" +
	"\x04root\x18\x02 \x01(\v2'.hadoop.hdfs.fsimage.INodeSection.INodeR\x04root\"\xc0\x06\n" +
	"\x13SnapshotDiffSection\x1a&\n" +
	"\x10CreatedListEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\fR\x04name\x1a\xe5\x02\n" +
	"\rDirectoryDiff\x12\x1e\n" +
	"\n" +
	"snapshotId\x18\x01 \x01(\rR\n" +
	"snapshotId\x12\"\n" +
	"\fchildrenSize\x18\x02 \x01(\rR\fchildrenSize\x12&\n" +
	"\x0eisSnapshotRoot\x18\x03 \x01(\bR\x0eisSnapshotRoot\x12\x12\n" +
	"\x04name\x18\x04 \x01(\fR\x04name\x12T\n" +
	"\fsnapshotCopy\x18\x05 \x01(\v20.hadoop.hdfs.fsimage.INodeSection.INodeDirectoryR\fsnapshotCopy\x12(\n" +
	"\x0fcreatedListSize\x18\x06 \x01(\rR\x0fcreatedListSize\x12&\n" +
	"\fdeletedINode\x18\a \x03(\x04B\x02\x10\x01R\fdeletedINode\x12,\n" +
	"\x0fdeletedINodeRef\x18\b \x03(\rB\x02\x10\x01R\x0fdeletedINodeRef\x1a\xdc\x01\n" +
	"\bFileDiff\x12\x1e\n" +
	"\n" +
	"snapshotId\x18\x01 \x01(\rR\n" +
	"snapshotId\x12\x1a\n" +
	"\bfileSize\x18\x02 \x01(\x04R\bfileSize\x12\x12\n" +
	"\x04name\x18\x03 \x01(\fR\x04name\x12O\n" +
	"\fsnapshotCopy\x18\x04 \x01(\v2+.hadoop.hdfs.fsimage.INodeSection.INodeFileR\fsnapshotCopy\x12/\n" +
	"\x06blocks\x18\x05 \x03(\v2\x17.hadoop.hdfs.BlockProtoR\x06blocks\x1a\xb9\x01\n" +
	"\tDiffEntry\x12K\n" +
	"\x04type\x18\x01 \x02(\x0e27.hadoop.hdfs.fsimage.SnapshotDiffSection.DiffEntry.TypeR\x04type\x12\x18\n" +
	"\ainodeId\x18\x02 \x01(\x04R\ainodeId\x12\x1c\n" +
	"\tnumOfDiff\x18\x03 \x01(\rR\tnumOfDiff\"'\n" +
	"\x04Type\x12\f\n" +
	"\bFILEDIFF\x10\x01\x12\x11\n" +
	"\rDIRECTORYDIFF\x10\x02\"z\n" +
	"\x12StringTableSection\x12\x1a\n" +
	"\bnumEntry\x18\x01 \x01(\rR\bnumEntry\x12\x1d\n" +
	"\bmaskBits\x18\x02 \x01(\r:\x010R\bmaskBits\x1a)\n" +
	"\x05Entry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x10\n" +
	"\x03str\x18\x02 \x01(\tR\x03str\"\x8a\x04\n" +
	"\x14SecretManagerSection\x12\x1c\n" +
	"\tcurrentId\x18\x01 \x01(\rR\tcurrentId\x120\n" +
	"\x13tokenSequenceNumber\x18\x02 \x01(\rR\x13tokenSequenceNumber\x12\x18\n" +
	"\anumKeys\x18\x03 \x01(\rR\anumKeys\x12\x1c\n" +
	"\tnumTokens\x18\x04 \x01(\rR\tnumTokens\x1aQ\n" +
	"\rDelegationKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1e\n" +
	"\n" +
	"expiryDate\x18\x02 \x01(\x04R\n" +
	"expiryDate\x12\x10\n" +
	"\x03key\x18\x03 \x01(\fR\x03key\x1a\x96\x02\n" +
	"\fPersistToken\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12\x18\n" +
	"\arenewer\x18\x03 \x01(\tR\arenewer\x12\x1a\n" +
	"\brealUser\x18\x04 \x01(\tR\brealUser\x12\x1c\n" +
	"\tissueDate\x18\x05 \x01(\x04R\tissueDate\x12\x18\n" +
	"\amaxDate\x18\x06 \x01(\x04R\amaxDate\x12&\n" +
	"\x0esequenceNumber\x18\a \x01(\rR\x0esequenceNumber\x12 \n" +
	"\vmasterKeyId\x18\b \x01(\rR\vmasterKeyId\x12\x1e\n" +
	"\n" +
	"expiryDate\x18\t \x01(\x04R\n" +
	"expiryDate\"\x81\x01\n" +
	"\x13CacheManagerSection\x12(\n" +
	"\x0fnextDirectiveId\x18\x01 \x02(\x04R\x0fnextDirectiveId\x12\x1a\n" +
	"\bnumPools\x18\x02 \x02(\rR\bnumPools\x12$\n" +
	"\rnumDirectives\x18\x03 \x02(\rR\rnumDirectives\"Y\n" +
	"\x14ErasureCodingSection\x12A\n" +
	"\bpolicies\x18\x01 \x03(\v2%.hadoop.hdfs.ErasureCodingPolicyProtoR\bpoliciesBk\n" +
	"&org.apache.hadoop.hdfs.server.namenodeB\fFsImageProtoZ3github.com/nirvam/go-hdfs-fsimage/pkg/fsimage/types"

var (
	file_fsimage_proto_rawDescOnce sync.Once
	file_fsimage_proto_rawDescData []byte
)

func file_fsimage_proto_rawDescGZIP() []byte {
	file_fsimage_proto_rawDescOnce.Do(func() {
		file_fsimage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fsimage_proto_rawDesc), len(file_fsimage_proto_rawDesc)))
	})
	return file_fsimage_proto_rawDescData
}

var file_fsimage_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_fsimage_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_fsimage_proto_goTypes = []any{
	(INodeSection_INode_Type)(0),                                     // 0: hadoop.hdfs.fsimage.INodeSection.INode.Type
	(SnapshotDiffSection_DiffEntry_Type)(0),                          // 1: hadoop.hdfs.fsimage.SnapshotDiffSection.DiffEntry.Type
	(*FileSummary)(nil),                                              // 2: hadoop.hdfs.fsimage.FileSummary
	(*NameSystemSection)(nil),                                        // 3: hadoop.hdfs.fsimage.NameSystemSection
	(*INodeSection)(nil),                                             // 4: hadoop.hdfs.fsimage.INodeSection
	(*FilesUnderConstructionSection)(nil),                            // 5: hadoop.hdfs.fsimage.FilesUnderConstructionSection
	(*INodeDirectorySection)(nil),                                    // 6: hadoop.hdfs.fsimage.INodeDirectorySection
	(*INodeReferenceSection)(nil),                                    // 7: hadoop.hdfs.fsimage.INodeReferenceSection
	(*SnapshotSection)(nil),                                          // 8: hadoop.hdfs.fsimage.SnapshotSection
	(*SnapshotDiffSection)(nil),                                      // 9: hadoop.hdfs.fsimage.SnapshotDiffSection
	(*StringTableSection)(nil),                                       // 10: hadoop.hdfs.fsimage.StringTableSection
	(*SecretManagerSection)(nil),                                     // 11: hadoop.hdfs.fsimage.SecretManagerSection
	(*CacheManagerSection)(nil),                                      // 12: hadoop.hdfs.fsimage.CacheManagerSection
	(*ErasureCodingSection)(nil),                                     // 13: hadoop.hdfs.fsimage.ErasureCodingSection
	(*FileSummary_Section)(nil),                                      // 14: hadoop.hdfs.fsimage.FileSummary.Section
	(*INodeSection_FileUnderConstructionFeature)(nil),                // 15: hadoop.hdfs.fsimage.INodeSection.FileUnderConstructionFeature
	(*INodeSection_AclFeatureProto)(nil),                             // 16: hadoop.hdfs.fsimage.INodeSection.AclFeatureProto
	(*INodeSection_XAttrCompactProto)(nil),                           // 17: hadoop.hdfs.fsimage.INodeSection.XAttrCompactProto
	(*INodeSection_XAttrFeatureProto)(nil),                           // 18: hadoop.hdfs.fsimage.INodeSection.XAttrFeatureProto
	(*INodeSection_INodeFile)(nil),                                   // 19: hadoop.hdfs.fsimage.INodeSection.INodeFile
	(*INodeSection_QuotaByStorageTypeEntryProto)(nil),                // 20: hadoop.hdfs.fsimage.INodeSection.QuotaByStorageTypeEntryProto
	(*INodeSection_QuotaByStorageTypeFeatureProto)(nil),              // 21: hadoop.hdfs.fsimage.INodeSection.QuotaByStorageTypeFeatureProto
	(*INodeSection_INodeDirectory)(nil),                              // 22: hadoop.hdfs.fsimage.INodeSection.INodeDirectory
	(*INodeSection_INodeSymlink)(nil),                                // 23: hadoop.hdfs.fsimage.INodeSection.INodeSymlink
	(*INodeSection_INode)(nil),                                       // 24: hadoop.hdfs.fsimage.INodeSection.INode
	(*FilesUnderConstructionSection_FileUnderConstructionEntry)(nil), // 25: hadoop.hdfs.fsimage.FilesUnderConstructionSection.FileUnderConstructionEntry
	(*INodeDirectorySection_DirEntry)(nil),                           // 26: hadoop.hdfs.fsimage.INodeDirectorySection.DirEntry
	(*INodeReferenceSection_INodeReference)(nil),                     // 27: hadoop.hdfs.fsimage.INodeReferenceSection.INodeReference
	(*SnapshotSection_Snapshot)(nil),                                 // 28: hadoop.hdfs.fsimage.SnapshotSection.Snapshot
	(*SnapshotDiffSection_CreatedListEntry)(nil),                     // 29: hadoop.hdfs.fsimage.SnapshotDiffSection.CreatedListEntry
	(*SnapshotDiffSection_DirectoryDiff)(nil),                        // 30: hadoop.hdfs.fsimage.SnapshotDiffSection.DirectoryDiff
	(*SnapshotDiffSection_FileDiff)(nil),                             // 31: hadoop.hdfs.fsimage.SnapshotDiffSection.FileDiff
	(*SnapshotDiffSection_DiffEntry)(nil),                            // 32: hadoop.hdfs.fsimage.SnapshotDiffSection.DiffEntry
	(*StringTableSection_Entry)(nil),                                 // 33: hadoop.hdfs.fsimage.StringTableSection.Entry
	(*SecretManagerSection_DelegationKey)(nil),                       // 34: hadoop.hdfs.fsimage.SecretManagerSection.DelegationKey
	(*SecretManagerSection_PersistToken)(nil),                        // 35: hadoop.hdfs.fsimage.SecretManagerSection.PersistToken
	(*ErasureCodingPolicyProto)(nil),                                 // 36: hadoop.hdfs.ErasureCodingPolicyProto
	(*BlockProto)(nil),                                               // 37: hadoop.hdfs.BlockProto
	(BlockTypeProto)(0),                                              // 38: hadoop.hdfs.BlockTypeProto
	(StorageTypeProto)(0),                                            // 39: hadoop.hdfs.StorageTypeProto
}
var file_fsimage_proto_depIdxs = []int32{
	14, // 0: hadoop.hdfs.fsimage.FileSummary.sections:type_name -> hadoop.hdfs.fsimage.FileSummary.Section
	36, // 1: hadoop.hdfs.fsimage.ErasureCodingSection.policies:type_name -> hadoop.hdfs.ErasureCodingPolicyProto
	17, // 2: hadoop.hdfs.fsimage.INodeSection.XAttrFeatureProto.xAttrs:type_name -> hadoop.hdfs.fsimage.INodeSection.XAttrCompactProto
	37, // 3: hadoop.hdfs.fsimage.INodeSection.INodeFile.blocks:type_name -> hadoop.hdfs.BlockProto
	15, // 4: hadoop.hdfs.fsimage.INodeSection.INodeFile.fileUC:type_name -> hadoop.hdfs.fsimage.INodeSection.FileUnderConstructionFeature
	16, // 5: hadoop.hdfs.fsimage.INodeSection.INodeFile.acl:type_name -> hadoop.hdfs.fsimage.INodeSection.AclFeatureProto
	18, // 6: hadoop.hdfs.fsimage.INodeSection.INodeFile.xAttrs:type_name -> hadoop.hdfs.fsimage.INodeSection.XAttrFeatureProto
	38, // 7: hadoop.hdfs.fsimage.INodeSection.INodeFile.blockType:type_name -> hadoop.hdfs.BlockTypeProto
	39, // 8: hadoop.hdfs.fsimage.INodeSection.QuotaByStorageTypeEntryProto.storageType:type_name -> hadoop.hdfs.StorageTypeProto
	20, // 9: hadoop.hdfs.fsimage.INodeSection.QuotaByStorageTypeFeatureProto.quotas:type_name -> hadoop.hdfs.fsimage.INodeSection.QuotaByStorageTypeEntryProto
	16, // 10: hadoop.hdfs.fsimage.INodeSection.INodeDirectory.acl:type_name -> hadoop.hdfs.fsimage.INodeSection.AclFeatureProto
	18, // 11: hadoop.hdfs.fsimage.INodeSection.INodeDirectory.xAttrs:type_name -> hadoop.hdfs.fsimage.INodeSection.XAttrFeatureProto
	21, // 12: hadoop.hdfs.fsimage.INodeSection.INodeDirectory.typeQuotas:type_name -> hadoop.hdfs.fsimage.INodeSection.QuotaByStorageTypeFeatureProto
	0,  // 13: hadoop.hdfs.fsimage.INodeSection.INode.type:type_name -> hadoop.hdfs.fsimage.INodeSection.INode.Type
	19, // 14: hadoop.hdfs.fsimage.INodeSection.INode.file:type_name -> hadoop.hdfs.fsimage.INodeSection.INodeFile
	22, // 15: hadoop.hdfs.fsimage.INodeSection.INode.directory:type_name -> hadoop.hdfs.fsimage.INodeSection.INodeDirectory
	23, // 16: hadoop.hdfs.fsimage.INodeSection.INode.symlink:type_name -> hadoop.hdfs.fsimage.INodeSection.INodeSymlink
	24, // 17: hadoop.hdfs.fsimage.SnapshotSection.Snapshot.root:type_name -> hadoop.hdfs.fsimage.INodeSection.INode
	22, // 18: hadoop.hdfs.fsimage.SnapshotDiffSection.DirectoryDiff.snapshotCopy:type_name -> hadoop.hdfs.fsimage.INodeSection.INodeDirectory
	19, // 19: hadoop.hdfs.fsimage.SnapshotDiffSection.FileDiff.snapshotCopy:type_name -> hadoop.hdfs.fsimage.INodeSection.INodeFile
	37, // 20: hadoop.hdfs.fsimage.SnapshotDiffSection.FileDiff.blocks:type_name -> hadoop.hdfs.BlockProto
	1,  // 21: hadoop.hdfs.fsimage.SnapshotDiffSection.DiffEntry.type:type_name -> hadoop.hdfs.fsimage.SnapshotDiffSection.DiffEntry.Type
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_fsimage_proto_init() }
func file_fsimage_proto_init() {
	if File_fsimage_proto != nil {
		return
	}
	file_hdfs_proto_init()
	file_acl_proto_init()
	file_xattr_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fsimage_proto_rawDesc), len(file_fsimage_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fsimage_proto_goTypes,
		DependencyIndexes: file_fsimage_proto_depIdxs,
		EnumInfos:         file_fsimage_proto_enumTypes,
		MessageInfos:      file_fsimage_proto_msgTypes,
	}.Build()
	File_fsimage_proto = out.File
	file_fsimage_proto_goTypes = nil
	file_fsimage_proto_depIdxs = nil
}
