//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: xattr.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type XAttrSetFlagProto int32

const (
	XAttrSetFlagProto_XATTR_CREATE  XAttrSetFlagProto = 1
	XAttrSetFlagProto_XATTR_REPLACE XAttrSetFlagProto = 2
)

// Enum value maps for XAttrSetFlagProto.
var (
	XAttrSetFlagProto_name = map[int32]string{
		1: "XATTR_CREATE",
		2: "XATTR_REPLACE",
	}
	XAttrSetFlagProto_value = map[string]int32{
		"XATTR_CREATE":  1,
		"XATTR_REPLACE": 2,
	}
)

func (x XAttrSetFlagProto) Enum() *XAttrSetFlagProto {
	p := new(XAttrSetFlagProto)
	*p = x
	return p
}

func (x XAttrSetFlagProto) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (XAttrSetFlagProto) Descriptor() protoreflect.EnumDescriptor {
	return file_xattr_proto_enumTypes[0].Descriptor()
}

func (XAttrSetFlagProto) Type() protoreflect.EnumType {
	return &file_xattr_proto_enumTypes[0]
}

func (x XAttrSetFlagProto) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *XAttrSetFlagProto) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = XAttrSetFlagProto(num)
	return nil
}

// Deprecated: Use XAttrSetFlagProto.Descriptor instead.
func (XAttrSetFlagProto) EnumDescriptor() ([]byte, []int) {
	return file_xattr_proto_rawDescGZIP(), []int{0}
}

type XAttrProto_XAttrNamespaceProto int32

const (
	XAttrProto_USER     XAttrProto_XAttrNamespaceProto = 0
	XAttrProto_TRUSTED  XAttrProto_XAttrNamespaceProto = 1
	XAttrProto_SECURITY XAttrProto_XAttrNamespaceProto = 2
	XAttrProto_SYSTEM   XAttrProto_XAttrNamespaceProto = 3
	XAttrProto_RAW      XAttrProto_XAttrNamespaceProto = 4
)

// Enum value maps for XAttrProto_XAttrNamespaceProto.
var (
	XAttrProto_XAttrNamespaceProto_name = map[int32]string{
		0: "USER",
		1: "TRUSTED",
		2: "SECURITY",
		3: "SYSTEM",
		4: "RAW",
	}
	XAttrProto_XAttrNamespaceProto_value = map[string]int32{
		"USER":     0,
		"TRUSTED":  1,
		"SECURITY": 2,
		"SYSTEM":   3,
		"RAW":      4,
	}
)

func (x XAttrProto_XAttrNamespaceProto) Enum() *XAttrProto_XAttrNamespaceProto {
	p := new(XAttrProto_XAttrNamespaceProto)
	*p = x
	return p
}

func (x XAttrProto_XAttrNamespaceProto) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (XAttrProto_XAttrNamespaceProto) Descriptor() protoreflect.EnumDescriptor {
	return file_xattr_proto_enumTypes[1].Descriptor()
}

func (XAttrProto_XAttrNamespaceProto) Type() protoreflect.EnumType {
	return &file_xattr_proto_enumTypes[1]
}

func (x XAttrProto_XAttrNamespaceProto) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *XAttrProto_XAttrNamespaceProto) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = XAttrProto_XAttrNamespaceProto(num)
	return nil
}

// Deprecated: Use XAttrProto_XAttrNamespaceProto.Descriptor instead.
func (XAttrProto_XAttrNamespaceProto) EnumDescriptor() ([]byte, []int) {
	return file_xattr_proto_rawDescGZIP(), []int{0, 0}
}

type XAttrProto struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Namespace     *XAttrProto_XAttrNamespaceProto `protobuf:"varint,1,req,name=namespace,enum=hadoop.hdfs.XAttrProto_XAttrNamespaceProto" json:"namespace,omitempty"`
	Name          *string                         `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Value         []byte                          `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XAttrProto) Reset() {
	*x = XAttrProto{}
	mi := &file_xattr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XAttrProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XAttrProto) ProtoMessage() {}

func (x *XAttrProto) ProtoReflect() protoreflect.Message {
	mi := &file_xattr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XAttrProto.ProtoReflect.Descriptor instead.
func (*XAttrProto) Descriptor() ([]byte, []int) {
	return file_xattr_proto_rawDescGZIP(), []int{0}
}

func (x *XAttrProto) GetNamespace() XAttrProto_XAttrNamespaceProto {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return XAttrProto_USER
}

func (x *XAttrProto) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *XAttrProto) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type SetXAttrRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Src           *string                `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	XAttr         *XAttrProto            `protobuf:"bytes,2,opt,name=xAttr" json:"xAttr,omitempty"`
	Flag          *uint32                `protobuf:"varint,3,opt,name=flag" json:"flag,omitempty"` //bits set using XAttrSetFlagProto
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetXAttrRequestProto) Reset() {
	*x = SetXAttrRequestProto{}
	mi := &file_xattr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetXAttrRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetXAttrRequestProto) ProtoMessage() {}

func (x *SetXAttrRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_xattr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetXAttrRequestProto.ProtoReflect.Descriptor instead.
func (*SetXAttrRequestProto) Descriptor() ([]byte, []int) {
	return file_xattr_proto_rawDescGZIP(), []int{1}
}

func (x *SetXAttrRequestProto) GetSrc() string {
	if x != nil && x.Src != nil {
		return *x.Src
	}
	return ""
}

func (x *SetXAttrRequestProto) GetXAttr() *XAttrProto {
	if x != nil {
		return x.XAttr
	}
	return nil
}

func (x *SetXAttrRequestProto) GetFlag() uint32 {
	if x != nil && x.Flag != nil {
		return *x.Flag
	}
	return 0
}

type SetXAttrResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetXAttrResponseProto) Reset() {
	*x = SetXAttrResponseProto{}
	mi := &file_xattr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetXAttrResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetXAttrResponseProto) ProtoMessage() {}

func (x *SetXAttrResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_xattr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetXAttrResponseProto.ProtoReflect.Descriptor instead.
func (*SetXAttrResponseProto) Descriptor() ([]byte, []int) {
	return file_xattr_proto_rawDescGZIP(), []int{2}
}

type GetXAttrsRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Src           *string                `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	XAttrs        []*XAttrProto          `protobuf:"bytes,2,rep,name=xAttrs" json:"xAttrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetXAttrsRequestProto) Reset() {
	*x = GetXAttrsRequestProto{}
	mi := &file_xattr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetXAttrsRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetXAttrsRequestProto) ProtoMessage() {}

func (x *GetXAttrsRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_xattr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetXAttrsRequestProto.ProtoReflect.Descriptor instead.
func (*GetXAttrsRequestProto) Descriptor() ([]byte, []int) {
	return file_xattr_proto_rawDescGZIP(), []int{3}
}

func (x *GetXAttrsRequestProto) GetSrc() string {
	if x != nil && x.Src != nil {
		return *x.Src
	}
	return ""
}

func (x *GetXAttrsRequestProto) GetXAttrs() []*XAttrProto {
	if x != nil {
		return x.XAttrs
	}
	return nil
}

type GetXAttrsResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	XAttrs        []*XAttrProto          `protobuf:"bytes,1,rep,name=xAttrs" json:"xAttrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetXAttrsResponseProto) Reset() {
	*x = GetXAttrsResponseProto{}
	mi := &file_xattr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetXAttrsResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetXAttrsResponseProto) ProtoMessage() {}

func (x *GetXAttrsResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_xattr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetXAttrsResponseProto.ProtoReflect.Descriptor instead.
func (*GetXAttrsResponseProto) Descriptor() ([]byte, []int) {
	return file_xattr_proto_rawDescGZIP(), []int{4}
}

func (x *GetXAttrsResponseProto) GetXAttrs() []*XAttrProto {
	if x != nil {
		return x.XAttrs
	}
	return nil
}

type ListXAttrsRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Src           *string                `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListXAttrsRequestProto) Reset() {
	*x = ListXAttrsRequestProto{}
	mi := &file_xattr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListXAttrsRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListXAttrsRequestProto) ProtoMessage() {}

func (x *ListXAttrsRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_xattr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListXAttrsRequestProto.ProtoReflect.Descriptor instead.
func (*ListXAttrsRequestProto) Descriptor() ([]byte, []int) {
	return file_xattr_proto_rawDescGZIP(), []int{5}
}

func (x *ListXAttrsRequestProto) GetSrc() string {
	if x != nil && x.Src != nil {
		return *x.Src
	}
	return ""
}

type ListXAttrsResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	XAttrs        []*XAttrProto          `protobuf:"bytes,1,rep,name=xAttrs" json:"xAttrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListXAttrsResponseProto) Reset() {
	*x = ListXAttrsResponseProto{}
	mi := &file_xattr_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListXAttrsResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListXAttrsResponseProto) ProtoMessage() {}

func (x *ListXAttrsResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_xattr_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListXAttrsResponseProto.ProtoReflect.Descriptor instead.
func (*ListXAttrsResponseProto) Descriptor() ([]byte, []int) {
	return file_xattr_proto_rawDescGZIP(), []int{6}
}

func (x *ListXAttrsResponseProto) GetXAttrs() []*XAttrProto {
	if x != nil {
		return x.XAttrs
	}
	return nil
}

type RemoveXAttrRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Src           *string                `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	XAttr         *XAttrProto            `protobuf:"bytes,2,opt,name=xAttr" json:"xAttr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveXAttrRequestProto) Reset() {
	*x = RemoveXAttrRequestProto{}
	mi := &file_xattr_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveXAttrRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveXAttrRequestProto) ProtoMessage() {}

func (x *RemoveXAttrRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_xattr_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveXAttrRequestProto.ProtoReflect.Descriptor instead.
func (*RemoveXAttrRequestProto) Descriptor() ([]byte, []int) {
	return file_xattr_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveXAttrRequestProto) GetSrc() string {
	if x != nil && x.Src != nil {
		return *x.Src
	}
	return ""
}

func (x *RemoveXAttrRequestProto) GetXAttr() *XAttrProto {
	if x != nil {
		return x.XAttr
	}
	return nil
}

type RemoveXAttrResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveXAttrResponseProto) Reset() {
	*x = RemoveXAttrResponseProto{}
	mi := &file_xattr_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveXAttrResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveXAttrResponseProto) ProtoMessage() {}

func (x *RemoveXAttrResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_xattr_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveXAttrResponseProto.ProtoReflect.Descriptor instead.
func (*RemoveXAttrResponseProto) Descriptor() ([]byte, []int) {
	return file_xattr_proto_rawDescGZIP(), []int{8}
}

var File_xattr_proto protoreflect.FileDescriptor

const file_xattr_proto_rawDesc = "" +
	"\n" +
	"\vxattr.proto\x12\vhadoop.hdfs\"\xd2\x01\n" +
	"\n" +
	"XAttrProto\x12I\n" +
	"\tnamespace\x18\x01 \x02(\x0e2+.hadoop.hdfs.XAttrProto.XAttrNamespaceProtoR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x02(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"O\n" +
	"\x13XAttrNamespaceProto\x12\b\n" +
	"\x04USER\x10\x00\x12\v\n" +
	"\aTRUSTED\x10\x01\x12\f\n" +
	"\bSECURITY\x10\x02\x12\n" +
	"\n" +
	"\x06SYSTEM\x10\x03\x12\a\n" +
	"\x03RAW\x10\x04\"k\n" +
	"\x14SetXAttrRequestProto\x12\x10\n" +
	"\x03src\x18\x01 \x02(\tR\x03src\x12-\n" +
	"\x05xAttr\x18\x02 \x01(\v2\x17.hadoop.hdfs.XAttrProtoR\x05xAttr\x12\x12\n" +
	"\x04flag\x18\x03 \x01(\rR\x04flag\"\x17\n" +
	"\x15SetXAttrResponseProto\"Z\n" +
	"\x15GetXAttrsRequestProto\x12\x10\n" +
	"\x03src\x18\x01 \x02(\tR\x03src\x12/\n" +
	"\x06xAttrs\x18\x02 \x03(\v2\x17.hadoop.hdfs.XAttrProtoR\x06xAttrs\"I\n" +
	"\x16GetXAttrsResponseProto\x12/\n" +
	"\x06xAttrs\x18\x01 \x03(\v2\x17.hadoop.hdfs.XAttrProtoR\x06xAttrs\"*\n" +
	"\x16ListXAttrsRequestProto\x12\x10\n" +
	"\x03src\x18\x01 \x02(\tR\x03src\"J\n" +
	"\x17ListXAttrsResponseProto\x12/\n" +
	"\x06xAttrs\x18\x01 \x03(\v2\x17.hadoop.hdfs.XAttrProtoR\x06xAttrs\"Z\n" +
	"\x17RemoveXAttrRequestProto\x12\x10\n" +
	"\x03src\x18\x01 \x02(\tR\x03src\x12-\n" +
	"\x05xAttr\x18\x02 \x01(\v2\x17.hadoop.hdfs.XAttrProtoR\x05xAttr\"\x1a\n" +
	"\x18RemoveXAttrResponseProto*8\n" +
	"\x11XAttrSetFlagProto\x12\x10\n" +
	"\fXATTR_CREATE\x10\x01\x12\x11\n" +
	"\rXATTR_REPLACE\x10\x02Bl\n" +
	"%org.apache.hadoop.hdfs.protocol.protoB\vXAttrProtosZ3github.com/nirvam/go-hdfs-fsimage/pkg/fsimage/types\xa0\x01\x01"

var (
	file_xattr_proto_rawDescOnce sync.Once
	file_xattr_proto_rawDescData []byte
)

func file_xattr_proto_rawDescGZIP() []byte {
	file_xattr_proto_rawDescOnce.Do(func() {
		file_xattr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xattr_proto_rawDesc), len(file_xattr_proto_rawDesc)))
	})
	return file_xattr_proto_rawDescData
}

var file_xattr_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_xattr_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_xattr_proto_goTypes = []any{
	(XAttrSetFlagProto)(0),              // 0: hadoop.hdfs.XAttrSetFlagProto
	(XAttrProto_XAttrNamespaceProto)(0), // 1: hadoop.hdfs.XAttrProto.XAttrNamespaceProto
	(*XAttrProto)(nil),                  // 2: hadoop.hdfs.XAttrProto
	(*SetXAttrRequestProto)(nil),        // 3: hadoop.hdfs.SetXAttrRequestProto
	(*SetXAttrResponseProto)(nil),       // 4: hadoop.hdfs.SetXAttrResponseProto
	(*GetXAttrsRequestProto)(nil),       // 5: hadoop.hdfs.GetXAttrsRequestProto
	(*GetXAttrsResponseProto)(nil),      // 6: hadoop.hdfs.GetXAttrsResponseProto
	(*ListXAttrsRequestProto)(nil),      // 7: hadoop.hdfs.ListXAttrsRequestProto
	(*ListXAttrsResponseProto)(nil),     // 8: hadoop.hdfs.ListXAttrsResponseProto
	(*RemoveXAttrRequestProto)(nil),     // 9: hadoop.hdfs.RemoveXAttrRequestProto
	(*RemoveXAttrResponseProto)(nil),    // 10: hadoop.hdfs.RemoveXAttrResponseProto
}
var file_xattr_proto_depIdxs = []int32{
	1, // 0: hadoop.hdfs.XAttrProto.namespace:type_name -> hadoop.hdfs.XAttrProto.XAttrNamespaceProto
	2, // 1: hadoop.hdfs.SetXAttrRequestProto.xAttr:type_name -> hadoop.hdfs.XAttrProto
	2, // 2: hadoop.hdfs.GetXAttrsRequestProto.xAttrs:type_name -> hadoop.hdfs.XAttrProto
	2, // 3: hadoop.hdfs.GetXAttrsResponseProto.xAttrs:type_name -> hadoop.hdfs.XAttrProto
	2, // 4: hadoop.hdfs.ListXAttrsResponseProto.xAttrs:type_name -> hadoop.hdfs.XAttrProto
	2, // 5: hadoop.hdfs.RemoveXAttrRequestProto.xAttr:type_name -> hadoop.hdfs.XAttrProto
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_xattr_proto_init() }
func file_xattr_proto_init() {
	if File_xattr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xattr_proto_rawDesc), len(file_xattr_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xattr_proto_goTypes,
		DependencyIndexes: file_xattr_proto_depIdxs,
		EnumInfos:         file_xattr_proto_enumTypes,
		MessageInfos:      file_xattr_proto_msgTypes,
	}.Build()
	File_xattr_proto = out.File
	file_xattr_proto_goTypes = nil
	file_xattr_proto_depIdxs = nil
}
